### ISSUE TITLE
OK to implement increments out of order?

### ISSUE THREAD

**Issue by geshuming** [nus-cs2103-AY1920S1/forum#1]
Is it an issue if we do some increments out of order? For example doing `A-Gradle` at the very beginning, before `Level-1`.

**Comment by damithc** [comment]
Good question. Normally, you should follow the given order, but `A-Gradle` is an exception. You can do it any time.

**Comment by geshuming** [comment]
Actually, I just realised that you can apply lightweight tags to the same commit multiple times. I suppose I can then tag the increment before/after `A-Gradle` with `A-Gradle`, thus keeping the tags in the same order. Thank you for the response professor.
