### ISSUE TITLE
Enabling Issue Tracker

### ISSUE THREAD

**Issue by lumwb** [nus-cs2103-AY1920S1/forum#10]
Hi, 

May I ask how I should enable the issue tracker in my repository and how I can verify that the CS2103T bot can track my commits / labels for the duke project.

The "issue" checkbox has already been ticked in my github settings (see picture below):
![image](https://user-images.githubusercontent.com/25117015/63502623-898e7f80-c500-11e9-8f86-1d615187aeec.png)

Thank you.

**Comment by damithc** [comment]
You have done it correctly 👍

**Comment by lumwb** [comment]
@damithc thanks prof!

Just to confirm, the setting was already checked before I received a notification from the CS2103T bot. Is there a way I can verify the bot has access the issues page of my repo?

**Comment by damithc** [comment]
> Just to confirm, the setting was already checked before I received a notification from the CS2103T bot. Is there a way I can verify the bot has access the issues page of my repo?

What notification? An email? Can you forward it to me?

**Comment by damithc** [comment]
Looks like the email was triggered by mistake while testing the script. It's fine if the issue tracker is enabled already.
