### ISSUE TITLE
The 100th issue

### ISSUE THREAD

**Issue by Parcly-Taxel** [nus-cs2103-AY1920S1/forum#100]
This is the 100th issue in this forum. Congratulations! :100:

I have a question for discussion. We are developing software that can quite easily be changed and tested, without much cost, and in doing so we are following some software engineering principles. However, there are some software projects where the relevant software **cannot** be changed once it is deployed, and where any error **is** fatal to the system (and possibly to people too).

![](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Parker_Solar_Probe.jpg/640px-Parker_Solar_Probe.jpg)

One example is the Parker Solar Probe (NASA illustration above). Because it goes so close to the sun, any error in the alignment of its solar shield **will** permanently damage its electronics. The same applies for almost all space probes and manned spaceflights.

What kinds of software engineering principles would apply to these special projects?

**Comment by damithc** [comment]
Interesting point @Parcly-Taxel 
Such software need to be highly-reliable and fault-tolerant. One technique that is used in this kind of situations is to have multiple implementations of critical parts of software. For example, when a binary decision needs to be taken, three alternative implementation compute the decision independently and the majority vote is used to decide which way to go. Also, multiple implementations can be used as fallback mechanisms. From what I remember, when Ariane-5 navigation system faced a problem, a secondary system took over (but that too failed).
