### ISSUE TITLE
Travis not auto-publishing docs

### ISSUE THREAD

**Issue by Ellieyee** [nus-cs2103-AY1920S1/forum#102]
## Environment

Describe your development environment

- IntelliJ version:
- Java version:
- Operating system version:
- _other packages' versions_

## Issue

Travis stopped auto-publishing docs https://github.com/AY1920S1-CS2103-T14-2/main/commits/gh-pages

I tried changing the github page source to master. But there is still no change. My local repo copy is also experiencing the same issue. Even though my repo shows the correct display, it's not being reflected in my team's github website and the module's Project List Page.

**Comment by damithc** [comment]
> I tried changing the github page source to master.

It should be gh-pages branch.
![image](https://user-images.githubusercontent.com/1673303/65858893-a046b280-e399-11e9-90ac-341948c60ba8.png)

**Comment by damithc** [comment]
Looking through your travis logs found this.
![image](https://user-images.githubusercontent.com/1673303/65859186-2c58da00-e39a-11e9-98df-1ef97a178fc9.png)

**Comment by Ellieyee** [comment]
Fixed the issue by setting a new access token. Thanks for your help prof!
