### ISSUE TITLE
Status for "Travis CI - branch" never arrives

### ISSUE THREAD

**Issue by Davidcwh** [nus-cs2103-AY1920S1/forum#105]
Please read up on how to write a [good question](https://stackoverflow.com/help/how-to-ask)

## Environment
- IntelliJ version: 2019.2
- Java version: 11.0.4
- Operating system version: Windows 10

## Issue
My teammates and I have been having this same problem where our pull requests from our forks get stuck on the last Travis check: **"Travis CI - Branch Expected — Waiting for status to be reported"**, but the status never arrives:

![travis-branch](https://user-images.githubusercontent.com/41605774/65929279-03852300-e434-11e9-8066-ed489c11dea6.png)

A [quick google search](https://travis-ci.community/t/travis-ci-branch-expected-waiting-for-status-to-be-reported/829) explains that we would need to have Travis enabled on our forks but that was already the case as shown:

![travis-passed](https://user-images.githubusercontent.com/41605774/65929312-2dd6e080-e434-11e9-9c22-885c01f62d1b.png)

![fork-passed](https://user-images.githubusercontent.com/41605774/65929339-46df9180-e434-11e9-9e34-211425db9f81.png)

It seems like the Travis record is not being fetched from our forks, did anyone else run into this problem and solved it? Any help would be greatly appreciated :)

**Comment by damithc** [comment]
Is this resolved? If not, can you give the link to a PR that has the said problem?
