### ISSUE TITLE
Tagging to the team repo

### ISSUE THREAD

**Issue by C-likethis123** [nus-cs2103-AY1920S1/forum#106]
The tutorial mentions we should use the 'git tag' feature to tag our team repo version as v1.1. However, our team cannot directly push to our team repo, and can only make PRs. 

How do we tag with our milestones if we cannot directly push to our team repo? Any guidance would be appreciated.

**Comment by ChrisKheng** [comment]
I think you can click on `releases` in the repo page of your team, then click on `new release`. You can then add a tag there which will tag the latest commit of your team repo.
<img width="747" alt="Screenshot 2019-10-01 at 4 32 51 PM" src="https://user-images.githubusercontent.com/42091735/65946677-401f4180-e469-11e9-94f5-980a309dd43c.png">

**Comment by damithc** [comment]
> However, our team cannot directly push to our team repo, and can only make PRs.

I suspect the person who has admin/owner privileges to the fork (most likely the one who created the fork) can still push to the repo without a PR.

**Comment by Parcly-Taxel** [comment]
The way to push the tags to the team repo from the command line is as follows:

* one who has write access to the team repo does `git tag -a "v1.1" -m "v1.1"` (the `-m` option is just for completeness), then `git push` on said team repo
* all team members do the same steps as detailed in #99 to get the tag on their forks, except that the `--tags` option is added to both commands
