### ISSUE TITLE
Can we switch to branching workflow?

### ISSUE THREAD

**Issue by shawnkoh** [nus-cs2103-AY1920S1/forum#108]
Hi Prof,
For the TP, we would like to stop using the forking workflow and instead adopt the [Git Feature Branch workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow#targetText=Git%20Feature%20Branch%20Workflow,without%20disturbing%20the%20main%20codebase.)
May I know if this is allowed?

**Comment by damithc** [comment]
You can adjust workflow from week 8 https://nus-cs2103-ay1920s1.github.io/website/schedule/week8/project.html#tp-mid-v1-2

**Comment by kylase-learning** [comment]
Forking workflow is a very common workflow in OSS as most of the time, a contributor doesn't have the right to the repository and therefore have to fork, make changes and submit the changes via PRs.
