### ISSUE TITLE
[Potential Spoilers] Questions on Lecture 7 Quiz (Part 1)

### ISSUE THREAD

**Issue by limerencee** [nus-cs2103-AY1920S1/forum#110]
Hello everyone, after doing the quiz, I am confused by some of the answers.

The following question's answer is `False`. Why is Bot considered not keeping track of Mat class? Bot has Mat attribute.
![question](https://user-images.githubusercontent.com/25873970/66126467-0fcbd480-e61c-11e9-86c7-3e96fecab417.png)

The following question's answer is `False`, with the reason being that: `This is not an association role. It's an association label.` Why is this not a valid diagram? In the textbook, the label `used by` is valid for Admin<->Student. From what I understand, these association labels are to describe the verb, so `helped by` should be a valid label.
![image](https://user-images.githubusercontent.com/25873970/66126703-aa2c1800-e61c-11e9-99f1-29298897d895.png)

The following question's answer is `False`, with the reason being that: `A Mat can have up to 5 helpers, not exactly 5 helpers.` The code shows `new Bot[5]` so that made me confused.
![image](https://user-images.githubusercontent.com/25873970/66126931-2aeb1400-e61d-11e9-83b9-fb534ccacdb2.png)

**Comment by joloong** [comment]
For the first question, I believe it is because it is stated in the question to only refer to the

> **highlighted association in the code**

**Comment by damithc** [comment]
> For the first question, I believe it is because it is stated in the question to only refer to the
> 
> > **highlighted association in the code**

Yes, that's correct. Thanks for the inputs @joloong 

2nd question: this question, and some others, ask if the diagram represents a specific aspect correctly (not if the diagram is valid in general). In this particular case, it asks if the _association role_ is depicted correctly -- i.e., it checks if you can distinguish between association _roles_ and association _labels_.

3rd question: An array of size 5 can hold 0 to 5 objects. While a multiplicity of 5 can be implemented as an array of size 5, we cannot deduce from an array of size 5 that the multiplicity is 5 (unless further information is given). The question is about going from code to diagram, not the other way around.

**Comment by limerencee** [comment]
Thank you for your replies, my doubts are cleared. :smile:
