### ISSUE TITLE
Labelling an issue which is not exactly the user story but part of the story.

### ISSUE THREAD

**Issue by Yehezkiel01** [nus-cs2103-AY1920S1/forum#119]
What should I label an issue which is not exactly the user story but part of the story?

For instance, my user story is "As a user I want to add a new contact".
Later on, I break it into 2 smaller issues, which are:
1. "Parse 'contact create' command into CreateCommand object"
2. "Implement CreateCommand object"

Should I label both of them as type.Task or type.Story?

**Comment by damithc** [comment]
Perhaps you can have one issue for the corresponding user story and these two can be considered as tasks under that issue. GitHub's task list notation can be useful for this case. Here is a PR that is using a similar technique: https://github.com/reposense/RepoSense/pull/902

**Comment by Yehezkiel01** [comment]
Thank you very much
