### ISSUE TITLE
Is there any way to double-check if cs2103 bot has access to my duke repository?

### ISSUE THREAD

**Issue by whneo97** [nus-cs2103-AY1920S1/forum#12]
After configuring my git username as according to the instructions on the cs2103 website last week, I submitted the pre-lecture survey and submitted the git username that I have configured.

However, I just noticed that despite not having tracking enabled, I did not receive any emails from cs2103 bot about it (like my friends did), nor received any other emails for any other purposes. It came to my realisation that my git username has been reset to my full name rather than the username I had previously configured (and suspect this was possibly due to entering the rm -R .git command last week in an attempt to reset some terminal display features that were affected by the setting up of git)

I have now enabled issues tracking, and reconfigured my username back to what I believe I previously submitted in the pre-lecture survey, but I'm not entirely sure whether it is correct.

Is there any way to double-check or confirm whether cs2103 bot is now able to track my progress on the duke repository that was forked on my account?

Thank you and sorry for any inconvenience caused.

**Comment by damithc** [comment]
Not to worry. It's fine as long as the issue tracker is enabled now. The script hasn't run yet. It sent out a few emails by mistake during a test run -- that's why some students received emails.

**Comment by whneo97** [comment]
Hi prof, thank you fo the reply and assurance! Will it be possible to check if my current git username corresponds to the one submitted in the pre-lecture survey?

**Comment by damithc** [comment]
> Hi prof, thank you fo the reply and assurance! Will it be possible to check if my current git username corresponds to the one submitted in the pre-lecture survey?

We didn't ask for git username. It was the GitHub username we collected, which I assume remains the same.

**Comment by whneo97** [comment]
Okay sure, yes should be the same, thank you prof for the clarification!

**Comment by sandydays** [comment]
I missed setting up the issue tracker even though I finished the levels before the deadline yesterday and committed the code. Realized only after bot sent me an email on this. Will this affect my iP deliverables for this week as recorded by the bot?
