### ISSUE TITLE
Request to use TMDB library

### ISSUE THREAD

**Issue by heze8** [nus-cs2103-AY1920S1/forum#120]
## Library

The Movie Database (TMDB)
https://www.themoviedb.org/documentation/api

## Purpose

Using it to get online information on movies and tv series if the user chooses to when connected to the internet.

**Comment by damithc** [comment]
Approved. Please note our [recommendation about using online APIs](https://nus-cs2103-ay1920s1.github.io/website/admin/project-constraints.html#tp-constraints).
