### ISSUE TITLE
Coveralls issue

### ISSUE THREAD

**Issue by WilliamRyank** [nus-cs2103-AY1920S1/forum#121]
Recently, coveralls do not show the statistics in our team's PR. Anyone has experienced his before? We did not modify any coveralls settings. Thank you

**Comment by damithc** [comment]
Does the problem still there?

**Comment by seanlowjk** [comment]
Do change the url to: 

`https://coveralls.io/repos/github/YOUR_REPOS/badge.svg?branch=master&service=github`for the image. 

Do let me know if there are still problems with your coveralls not updating.
