### ISSUE TITLE
Problem with iP Peer Evaluation on Luminus not saving properly.

### ISSUE THREAD

**Issue by briyanii** [nus-cs2103-AY1920S1/forum#122]
I had to close the survey before completing it, and load it again. 

However, I noticed that further changes to my response for question 12 are lost, even after I press the save for later button.

**Comment by damithc** [comment]
Looks like a LumiNUS bug. Perhaps report [here](https://cithelp.nus.edu.sg/servicedesk/customer/portal/8)?. It's best for you to report it as they usually want to follow up for more details.

**Comment by briyanii** [comment]
Actually I found out why it was not saving.

It was because I had some text with < > around it and it was being removed.
The text including and after the first <something> was removed

**Comment by damithc** [comment]
It is still a bug though. I noticed a similar behavior in quizzes and reported it earlier.
