### ISSUE TITLE
Remove SE-EDU navigation bar for tP product page?

### ISSUE THREAD

**Issue by TheRealRavager** [nus-cs2103-AY1920S1/forum#128]
Hi, can I check whether we are allowed/supposed to remove the SE-EDU navi bar? It says that we are to include it if the project is an official SE-EDU project but I'm not sure if that includes tP or whether its for educators to include in SE-EDU software.

![image](https://user-images.githubusercontent.com/43085796/66712628-1acbf500-edd2-11e9-83b0-eacf8a553904.png)

**Comment by damithc** [comment]
Allowed and recommended.

**Comment by TheRealRavager** [comment]
Thanks Prof!
