### ISSUE TITLE
Used ArrayList data structure right from the start

### ISSUE THREAD

**Issue by anqichen9856** [nus-cs2103-AY1920S1/forum#13]
I used ArrayList structure for storing tasks since Level-2, and added both tags "A-Collections" and "Level-2" to the same commit. Do I need to use Array instead and redo the levels?

**Comment by damithc** [comment]
No need @anqichen9856 . It's fine.

**Comment by anqichen9856** [comment]
@damithc I see. Thank you!

**Comment by damithc** [comment]
@anqichen9856 go ahead and close the issue if the question has been resolved.
