### ISSUE TITLE
Request to use JFreeChart

### ISSUE THREAD

**Issue by zhangxuan97** [nus-cs2103-AY1920S1/forum#130]
## Library

[JFreeChart](http://www.jfree.org/)

## Purpose

To generate charts to better visualise data and statistics.

**Comment by damithc** [comment]
What's their license type (or terms of use)?

**Comment by zhangxuan97** [comment]
[GNU Lesser General Public Licence](http://www.jfree.org/lgpl.php)

**Comment by damithc** [comment]
Approved.
