### ISSUE TITLE
Request to use RichTextFX

### ISSUE THREAD

**Issue by briyanii** [nus-cs2103-AY1920S1/forum#132]
## Library

[RichTextFX](https://github.com/FXMisc/RichTextFX)

## Purpose
Syntax highlighting in CLI and auto completion

## License

Dual-licensed under [BSD 2-Clause License](https://opensource.org/licenses/BSD-2-Clause) and [GPLv2 with the Classpath Exception](http://openjdk.java.net/legal/gplv2+ce.html).

**Comment by damithc** [comment]
Approved.
