### ISSUE TITLE
Repo Sense: issue with "invalid filepath"

### ISSUE THREAD

**Issue by huiminlim** [nus-cs2103-AY1920S1/forum#137]
## Environment

Describe your development environment

- IntelliJ version: IntelliJ IDEA Ultimate 2019.2.1
- Java version: java 11.0.2
- Operating system version: Windows 10
- _other packages' versions_

## Issue

I was trying to make RepoSense work in my local repo by trying the following instructions from this page:
https://github.com/reposense/RepoSense/blob/release/docs/UserGuide.md#configuring-a-repo-to-provide-additional-data-to-reposense

I added the config.json and followed all the way up to this step
`java -jar RepoSense.jar --repo  C:/Users/user/Desktop/tp/main`
where my RepoSense.jar exists.

However, RepoSense shows a "Invalid filepath" error, which I am not too sure why.

![image](https://user-images.githubusercontent.com/43434313/67087290-3588da00-f1d5-11e9-9838-bc6bad194394.png)

I also tried to go to the file path `.\\src\\test\\java\\dream\\fcard\\util\\data\\Test.java` in my code to check and commented out lines with slashes in related test files, but does not solve the issue as well.

This is the link to the filepath in github for easy reference: https://github.com/huiminlim/main/blob/master/src/test/java/dream/fcard/util/data/Test.java

Any advice on why this error exist? Thanks in advance!

## Code/Log Trace

My local repo currently has the code from this master branch: https://github.com/huiminlim/main

**Comment by damithc** [comment]
I've asked RepoSense devs to take a look

**Comment by huiminlim** [comment]
@damithc I think I resolved the problem, by removing a file with name " .\src\test\java\dream\fcard\util\data\Test.java " from my repo. Then, RepoSense produced a valid report after I removed this file with slashes in the name.

https://github.com/huiminlim/main/commit/c3215ba03a6d3d2c126d98f9b6c0b2376a3ffebc

Thank you and RepoSense dev team for the help anyway!
