### ISSUE TITLE
Level-8

### ISSUE THREAD

**Issue by CarbonGrid** [nus-cs2103-AY1920S1/forum#14]
How do we process the datetime requirement? 
Must the user provide a datetime or is it optional?
Do we strictly require user to provide entire datetime or do we allow for partial inputs?
E.g "22/08/2019 1300" vs "22/08/2019" or even "08/2019"

**Comment by damithc** [comment]
Up to you :-) Do the best you can.

**Comment by CarbonGrid** [comment]
Noted.
