### ISSUE TITLE
UML Diagrams with draw.io

### ISSUE THREAD

**Issue by tanlk99** [nus-cs2103-AY1920S1/forum#143]
Our team is currently using draw.io to create our UML diagrams. It has a feature to export diagrams as XML files. Should we then include these XML files inside the `docs/diagram` directory?

**Comment by damithc** [comment]
Can those XML files can be used in future for something, for example, to update the diagrams? If yes, then it makes sense to store them in the repo.

**Comment by tanlk99** [comment]
Yes, they can be used to update the diagrams. So we should store them in the docs/diagrams directory?

**Comment by damithc** [comment]
I'll let you decide where to store them. It's fine as long as they are versioned controlled together with the images (i.e., update both in the same commit).
