### ISSUE TITLE
How to depict static method calls in sequence diagram?

### ISSUE THREAD

**Issue by LeowWB** [nus-cs2103-AY1920S1/forum#145]
Refer to question title. If a class is never instantiated, we can still call static methods of that class. How would we show this in a sequence diagram? In particular, what would the entity tag show? Should it still show `:ClassName` even when we are not calling methods on an instance of the class?

**Comment by damithc** [comment]
Good question. You can use something like this:
![image](https://user-images.githubusercontent.com/1673303/67466838-542a1d80-f67a-11e9-9764-4b2d0ae48c0f.png)

**Comment by LeowWB** [comment]
Got it, thanks for the quick reply, prof!
