### ISSUE TITLE
Module website's description on PPP is incorrect

### ISSUE THREAD

**Issue by le0tan** [nus-cs2103-AY1920S1/forum#149]
In [this section](https://nus-cs2103-ay1920s1.github.io/website/admin/project-deliverables.html#deliverable-project-portfolio-page-ppp) of the module website, the format of the code contributed URL is incorrect. It should be:

https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#search=le0tan

where "le0tan" is replaced with your GitHub username.

**Comment by damithc** [comment]
Thanks for the bug report @le0tan 
Fixed.
