### ISSUE TITLE
Request to use Asciidoctor Gradle plugin 

### ISSUE THREAD

**Issue by hua-lun** [nus-cs2103-AY1920S1/forum#151]
## Library
Asciidoctor, a fast text processor & publishing toolchain for converting AsciiDoc to HTML5, DocBook & more.
[Asciidoctor](https://asciidoctor.org)

## Purpose
Use the library to help with the writing of adoc files for user/developer guide.
{Explain for what kind of functionality you intended to use it for}

## License
MIT License - https://github.com/asciidoctor/asciidoctor/blob/master/LICENSE 
{Mention the license under which the library is released (e.g., MIT, GPL, Apache etc.) and give a link to the relevant page on their website}

**Comment by thwnus** [comment]
Doesn't it [already](https://github.com/nus-cs2103-AY1920S1/addressbook-level3/blob/master/build.gradle#L13) [do so](https://github.com/nus-cs2103-AY1920S1/addressbook-level3/blob/master/build.gradle#L117-L144)?

**Comment by hua-lun** [comment]
oh right, I've missed it by accident. Thanks for the tip!
