### ISSUE TITLE
Project Root Directory

### ISSUE THREAD

**Issue by ChrisKheng** [nus-cs2103-AY1920S1/forum#16]
Hi prof, is the term "project root directory" refers to the "src/main/" folder or the topmost folder that consists of all the folders including "src/main/" ?

**Comment by j-lum** [comment]
The latter.

**Comment by tcgj** [comment]
Yup, basically the root directory is your main "duke" folder, which contains your .git directory, the src folder, and everything else.

**Comment by ChrisKheng** [comment]
Alright thanks!
