### ISSUE TITLE
Closing issues from the PE-D/PE

### ISSUE THREAD

**Issue by Parcly-Taxel** [nus-cs2103-AY1920S1/forum#161]
Can we close (but obviously not delete, since both repositories will be checked in the tutor grading) the bugs we created in the dedicated repositories for the practical exam dry run and (in two weeks' time) the practical exam itself?

**Comment by damithc** [comment]
No. Closed bug reports are considered as bug reports _withdrawn_ by the tester e.g., created by mistake in the first place. Our grading scripts will only consider open issues in PED and PE repos.

**Comment by Parcly-Taxel** [comment]
@damithc In any case, when can we mark them as closed?

**Comment by damithc** [comment]
@Parcly-Taxel Grading work continues until Dec 9th. You can close the issues after that.

**Comment by Parcly-Taxel** [comment]
I heard that some things I wanted to do could not be done until 2020, what are they?

**Comment by damithc** [comment]
A easy to remember guideline is not to touch the PE or PED issues until you receive your grade. After that, you can delete the PE and PED repos if you wish.

**Comment by whneo97** [comment]
Hi prof @damithc , sorry just to double-check, will the following then be correct?

- We are not to close the issues we posted until Dec 9th (unless we intend to withdraw them.

- For the PED issues posted on our team repo, we may close the issue by the bot as soon as we have resolved the problems described (?). However, we are not to close the corresponding issues opened by the original author. (?)

- For PE issues, we are not to rectify or close the issues at all, be it by the bot or by the original author. (?)

**Comment by damithc** [comment]
> * We are not to close the issues we posted until Dec 9th (unless we intend to withdraw them.
> * For the PED issues posted on our team repo, we may close the issue by the bot as soon as we have resolved the problems described (?). However, we are not to close the corresponding issues opened by the original author. (?)
> * For PE issues, we are not to rectify or close the issues at all, be it by the bot or by the original author. (?)

Yes, that's correct. You are free to do anything with the PED issues posted on your team repo. We do not take them for grading.

**Comment by whneo97** [comment]
> > * We are not to close the issues we posted until Dec 9th (unless we intend to withdraw them.
> > * For the PED issues posted on our team repo, we may close the issue by the bot as soon as we have resolved the problems described (?). However, we are not to close the corresponding issues opened by the original author. (?)
> > * For PE issues, we are not to rectify or close the issues at all, be it by the bot or by the original author. (?)
> 
> Yes, that's correct. You are free to do anything with the PED issues posted on your team repo. We do not take them for grading.

Okay noted, thank you prof for the clarification!
