### ISSUE TITLE
Request to use Jfeonix Library

### ISSUE THREAD

**Issue by Joanna-YJA** [nus-cs2103-AY1920S1/forum#163]
## Library
Jfeonix  https://github.com/jfoenixadmin/JFoenix

## Purpose
Jfeonix is a framework to create custom components for the Graphical User Interface. More specifically, JFXButton and JFXTextField is used. Can these components and the rest of the custom components in the library be used?

## License
Apache License 2.0

**Comment by damithc** [comment]
License?

**Comment by Joanna-YJA** [comment]
Apache License 2.0 is used.

**Comment by damithc** [comment]
Approved.
