### ISSUE TITLE
Request to use FontAwesomefx Library

### ISSUE THREAD

**Issue by Joanna-YJA** [nus-cs2103-AY1920S1/forum#164]
## Library 
FontAwesomefx  https://bitbucket.org/Jerady/fontawesomefx/src/master/

## Purpose
The library provides icons and vector graphics to be used in the Graphical User Interface.
{Explain for what kind of functionality you intende to use it for}

## License

FontAwesomeFX is licensed under the Apache 2.0 license.

**Comment by damithc** [comment]
Approved.
