### ISSUE TITLE
Request to use fuzzywuzzy library

### ISSUE THREAD

**Issue by neoshh** [nus-cs2103-AY1920S1/forum#166]
## Library

fuzzywuzzy
https://github.com/xdrop/fuzzywuzzy

## Purpose

To check user input against a list of correct answers for short answer questions to see if user answered the question correctly

## License

GNU General Public License v2.0
https://github.com/xdrop/fuzzywuzzy/blob/master/LICENSE

**Comment by damithc** [comment]
Approved
