### ISSUE TITLE
Travis build fails due to coveralls/asciidoctor

### ISSUE THREAD

**Issue by huiminlim** [nus-cs2103-AY1920S1/forum#167]
Please read up on how to write a [good question](https://stackoverflow.com/help/how-to-ask)

## Environment

Describe your development environment

- IntelliJ version: IntelliJ IDEA 2019.2.1
- Java version: 
- Operating system version: Windows 10
- _other packages' versions_

## Issue

I carried on my coding activities as per normal and I created a pull request to submit to my team repo. However, travis keeps failing my PR and codes even though the travis for my own repo passes and says that build is successful.

This is the screenshot of Travis (failed) build from my team repo:
![image](https://user-images.githubusercontent.com/43434313/68325466-6be6b480-0104-11ea-8a62-3dec340aa383.png)
This is the link:
https://travis-ci.org/AY1920S1-CS2103-F09-2/main/builds/608332992?utm_medium=notification&utm_source=github_status
Build number is #556

This is the screenshot of my own repo's Travis
![image](https://user-images.githubusercontent.com/43434313/68325558-a2243400-0104-11ea-93f3-18b1522bb763.png)

https://travis-ci.org/huiminlim/main/builds/608332966?utm_medium=notification&utm_source=github_status

**Comment by damithc** [comment]
@huiminlim what happens when you run the gradle task locally? Run that task only. Try to do that on Windows as well as Mac.

**Comment by huiminlim** [comment]
Hi Prof Damith, looks like this is the output i obtained on Windows 10, and no error is shown when I run both the gradle and just the task alone. Not sure if I did the correct way as you advised.

![image](https://user-images.githubusercontent.com/43434313/68523114-5aadcb80-02ef-11ea-9b28-c83dc176e3b0.png)

**Comment by huiminlim** [comment]
We executed the same command on a mac

This is the complete task
![image](https://user-images.githubusercontent.com/43434313/68523159-ede70100-02ef-11ea-8111-8b24a55171ff.png)

This is the asciidoctor only task
 
![image](https://user-images.githubusercontent.com/43434313/68523162-fb03f000-02ef-11ea-92d8-6fc4f6acfbae.png)

**Comment by geshuming** [comment]
You can try triggering a custom build on travis, and run `./gradlew asciidoctor --info` to see what could be causing the issue?

**Comment by geshuming** [comment]
Under "more options", click on the "Trigger build" option and insert a custom yaml config to 

![image](https://user-images.githubusercontent.com/43642522/68523268-a19cc080-02f1-11ea-94ee-78ed46680304.png)

**Comment by damithc** [comment]
@huiminlim looks like your master branch itself is failing. Perhaps you can remove asciidoctor task from the travis and get everything else to pass first? After that, open a new PR that adds back the asciidoctor task and try to fix the problem in that PR.

**Comment by huiminlim** [comment]
Hi Prof Damtih, @geshuming ,

If I comment out asciidoctor, the pages will not be deployed and build fails too
![image](https://user-images.githubusercontent.com/43434313/68524158-54731b80-02fe-11ea-9039-5b3487da1fa3.png)

If use --info, shows me this
![image](https://user-images.githubusercontent.com/43434313/68524171-72d91700-02fe-11ea-8d40-fc0c271db096.png)

**Comment by tuandingwei** [comment]
Try checking your test cases. It could be that you might have failed one of the test cases.

**Comment by shawnpunchew11** [comment]
@tuandingwei the cause of the error wasn't the test cases. I believe it was from either ASCIIDoctor or Coveralls as there is some dependency within the CI there. We tried commenting out asciidoctor or coveralls but both resulted in further errors because asciidoctor relies on coveralls do generate a html file that is required. we've gotten it to pass temporarily by commenting out our deploy segment within our gradle file but that affects our publication

**Comment by damithc** [comment]
One possibility is to run the asciidoctor task locally and push the generated html files to the gh-pages branch of the repo to simulate how Travis depoly the generated website.

**Comment by huiminlim** [comment]
Thanks Prof, that works.
