### ISSUE TITLE
Must I strictly complete minimal tasks before completing stretch goals?

### ISSUE THREAD

**Issue by C-likethis123** [nus-cs2103-AY1920S1/forum#17]
For level A-MoreOOP, I find it easier to create the 4 required classes and the Command class (specified in the stretch goal) from the start. 
Do I need to create the 4 required classes, tag the commit, before creating the Command class or can I just go ahead and create the Command class?

**Comment by damithc** [comment]
You can go for the stretch goal directly 👍

**Comment by shawnkoh** [comment]
What if we created the classes sporadically in prior commits? At which commit do we tag A-MoreOOP?

**Comment by damithc** [comment]
> What if we created the classes sporadically in prior commits? At which commit do we tag A-MoreOOP?

At any point when you think it meets the requirement for the increment.

**Comment by C-likethis123** [comment]
Okay, thanks everyone for your input!
