### ISSUE TITLE
Request to use iCal4j library

### ISSUE THREAD

**Issue by gabrielseow** [nus-cs2103-AY1920S1/forum#170]
## Library

iCal4j : https://github.com/ical4j

## Purpose

iCal4j library used to parse .ics calendar files for our application feature to compare timetables and schedule meetings during common available times.

## License

The license is owned by Ben Fortuna
URL: https://github.com/ical4j/ical4j/blob/develop/LICENSE.txt

**Comment by damithc** [comment]
Links not working

**Comment by gabrielseow** [comment]
Sorry, I updated the links

**Comment by damithc** [comment]
Approved.
