### ISSUE TITLE
Member detail not showing up on Project List page

### ISSUE THREAD

**Issue by dawo5010** [nus-cs2103-AY1920S1/forum#175]
Hi Prof,

One of my teammates does not have her profile picture available on the Project List webpage, despite it being uploaded. My guess was that it was not uploaded to the repo in all-lower caps. We've since fixed it (renamed to all lower caps).

Do we have to make sure that the photo shows up on the project list page before submission?
My group is CS2103T-T13-3. 

Thank you in advance!

**Comment by damithc** [comment]
The project list page pulls the photo from your website directly. If the the file is at the expected location, the photo should show up in the project list page immediately (barring any browser caching).

**Comment by dawo5010** [comment]
Ah yes, I just checked this morning that it's now showing. It was probably browser caching. Thanks Prof!
