### ISSUE TITLE
Format of HTML wrong when on website

### ISSUE THREAD

**Issue by junhuplim** [nus-cs2103-AY1920S1/forum#176]
## Environment

- Java version: 11
- Operating system version: macOS Catalina Version 10.15.1

## Issue

[Here is my UG which you can see has the wrong format](https://ay1920s1-cs2103t-t12-3.github.io/main/UserGuide.html)

## Code/Log Trace

[Here are the commits](https://github.com/AY1920S1-CS2103T-T12-3/main/commits/master)

I believe that it is this commit [#243](https://github.com/AY1920S1-CS2103T-T12-3/main/commit/40587285f4fa59dc89cc59c6557d40b13185bb79) that has caused the behaviour. However, I have pushed another commit that revert these changes but the format of HTML remains wrong.

Would appreciate any help! Thank you!
<img width="1438" alt="Screenshot 2019-11-11 at 11 25 03 AM" src="https://user-images.githubusercontent.com/48384672/68560340-ae4d2000-047b-11ea-896a-e3a5151a12e6.png">

**Comment by damithc** [comment]
Which commit caused this to appear at first?
Did you try reverting that commit?

**Comment by junhuplim** [comment]
Edited the question to be more informative! Yes I have pushed another commit to revert the changes.

**Comment by junhuplim** [comment]
Resolved! It is the presence of the whitespace at line 2 and 6 of the commit 
[#243](https://github.com/AY1920S1-CS2103T-T12-3/main/commit/40587285f4fa59dc89cc59c6557d40b13185bb79)

**Comment by damithc** [comment]
https://en.wikipedia.org/wiki/Rubber_duck_debugging :-)
