### ISSUE TITLE
Error For Team Tags When Using Catcher 

### ISSUE THREAD

**Issue by seanlowjk** [nus-cs2103-AY1920S1/forum#179]
It seems after Using Catcher, the Tags for the Team will change: 

![image](https://user-images.githubusercontent.com/42912708/68995823-0301f800-08cd-11ea-990d-4972c506814e.png)

Whereas the original tags are like this: 

![image](https://user-images.githubusercontent.com/42912708/68995826-0b5a3300-08cd-11ea-9522-d38a415d4ef5.png)

My question is: are we supposed to follow the team tags for the first or second photo? 
Thanks!

**Comment by damithc** [comment]
This happens when you use an older version of CATcher. Older version work for the testing phase, but not this phase. Please use the latest version.

**Comment by seanlowjk** [comment]
Ok thank you Prof! 👍
