### ISSUE TITLE
Encountering difficulties setting default formatting for IntelliJ

### ISSUE THREAD

**Issue by dawo5010** [nus-cs2103-AY1920S1/forum#18]
Hi,

I'm trying to get IntelliJ to be compliant with the [specified code style](https://nus-cs2103-ay1920s1.github.io/website/coding-standards/java/intermediate.html).

However, I seem to be having some difficulties with trying to get IntelliJ to save the settings:
![2019-08-27 10-07-32 2019-08-27 10_09_12](https://user-images.githubusercontent.com/4518827/63735579-ded8e100-c8b2-11e9-9d64-979ffd15183f.gif)

As can be seen from the gif, no matter how many times I try to get IntelliJ to accept the new settings, the indentation for switch cases resets upon clicking OK.

I've already unticked 'Detect and use existing file indents for editing.' but that hasn't helped.

Would appreciate if anyone has any insight into the issue, thank you!

**Comment by xinmingzh** [comment]
Instead of editing the code, click on the "Wrapping and Braces" option in the bar directly above the code, then scroll down and look for "'switch' statement" and untick "Indent case branches". The change will be reflected in the sample code.

**Comment by dawo5010** [comment]
Thanks! That fixed the formatting. Appreciate the help!

**Comment by damithc** [comment]
Thanks for the help @xinmingzh :+1:
