### ISSUE TITLE
What exactly constitutes a bug?

### ISSUE THREAD

**Issue by LeowWB** [nus-cs2103-AY1920S1/forum#181]
I am somewhat confused as to what constitutes a "bug" for the PE. Which of the following count as bugs?

1. Application behaves in a manner described in the UG, but this behavior is unintuitive/confusing to user, or does not make sense.

2. Application behaves in a manner described in the UG. UG notes that this behavior is expected for certain inputs, but instructs user not to enter such inputs.

3. Application feature does not support an operation. UG does not mention this operation at all, however, user thinks the operation should be supported.

**Comment by damithc** [comment]
> * Application behaves in a manner described in the UG, but this behavior is unintuitive/confusing to user, or does not make sense.

Can be categorized as a `FeatureFlaw`.

> * Application behaves in a manner described in the UG. UG notes that this behavior is expected for certain inputs, but instructs user not to enter such inputs.

Can be categorized as a `FeatureFlaw` if you think this situation should have been handled in a better way.

> * Application feature does not support an operation. UG does not mention this operation at all, however, user thinks the operation should be supported.

Can be categorized as a `FeatureFlaw`.

**Comment by LeowWB** [comment]
Alright, thanks, prof!
