### ISSUE TITLE
Constructors in UML

### ISSUE THREAD

**Issue by jeongyh99** [nus-cs2103-AY1920S1/forum#182]
How do you show constructors in UML? Is it a class level variable (underlined) or instance with return type same as the method name?

**Comment by damithc** [comment]
Can you give more details? For example, what kind of UML diagrams do you have in mind?

**Comment by jeongyh99** [comment]
My concern is the methods compartment for Class Diagrams. Thanks prof! 💯

**Comment by damithc** [comment]
> My concern is the methods compartment for Class Diagrams. Thanks prof!

In that case, treat it as any other method.

**Comment by jeongyh99** [comment]
Thank you!
