### ISSUE TITLE
Usage of VV

### ISSUE THREAD

**Issue by jeongyh99** [nus-cs2103-AY1920S1/forum#183]
Where any valid values are allowed in a test case, will we be penalized if we give the actual value instead? If so, what is the correct usage of VV (when do we use it as opposed to specifying the actual value?) Same goes for invalid values. Thank you!

**Comment by damithc** [comment]
VV = when using one valid value is as good as using any other i.e., exact value is irrelevant
Same for invalid values.

**Comment by damithc** [comment]
> Where any valid values are allowed in a test case, will we be penalized if we give the actual value instead?

Recommended to use VV when applicable.

**Comment by jeongyh99** [comment]
Thank you!
