### ISSUE TITLE
Issue: No Tests were found

### ISSUE THREAD

**Issue by jeongyh99** [nus-cs2103-AY1920S1/forum#19]
All the methods look fine, followed the steps as explained. java test directory marked as green with no error. However, when I right click the class and run 'Test' it says "No tests were found".

The only thing I did differently was that when the step 5 where the suggestion was for me to add JUnit 4, which I opted to get JUnit 5.4 instead . Not sure if that is the issue, I would appreciate if anyone could help me.

Thank you!

**Comment by damithc** [comment]
> The only thing I did differently was that when the step 5 where the suggestion was for me to add JUnit 4, which I opted to get JUnit 5.4 instead . Not sure if that is the issue, I would appreciate if anyone could help me.

Step 5 asks you to add JUnit 5 🤔 
![image](https://user-images.githubusercontent.com/1673303/63743160-f07bb200-c8cd-11e9-9f72-b0cc8cd66ff9.png)

**Comment by damithc** [comment]
You may want to post a screenshot showing all relevant areas of the IDE. That will provide more info for anyone willing to help you.

**Comment by jeongyh99** [comment]
![Result](https://user-images.githubusercontent.com/50542926/63745189-26bc3000-c8d4-11e9-885a-306966e8c254.PNG)
![TestCase](https://user-images.githubusercontent.com/50542926/63745192-26bc3000-c8d4-11e9-8016-4631c1cf0729.PNG)
![iml file](https://user-images.githubusercontent.com/50542926/63745194-26bc3000-c8d4-11e9-8532-2af97de77bde.PNG)
![Directories](https://user-images.githubusercontent.com/50542926/63745213-30459800-c8d4-11e9-8543-aea7b41f4e46.PNG)

Attached are the relevant screenshots! Once again thank you :-)

**Comment by damithc** [comment]
Are you able to run tests using these icons?
![image](https://user-images.githubusercontent.com/1673303/63745694-6e8f8700-c8d5-11e9-91c4-9a0fdcccfc7f.png)

**Comment by jeongyh99** [comment]
The icons when pressed are also unable to find the test cases.
Another method I tried but to do avail was by right clicking the methods in my code and generating each corresponding test method through IntelliJ, which also failed to detect my test cases.

**Comment by j-lum** [comment]
You seem to have an interesting directory/package structure. You might want to take a closer look at the `Run Configuration` of both your tests and `main`.

**Comment by damithc** [comment]
This is the expected directory structure (something along these lines), as seen on Intellij:
![image](https://user-images.githubusercontent.com/1673303/63751953-ed3ef100-c8e2-11e9-8421-2730ff697cf8.png)

**Comment by jeongyh99** [comment]
Thank you for the help! My directory used to look like that until i started introducing packages, I am still trying to figure out what the issue is with my structure. My Run Configuration looks fine, but I am probably missing out something. I feel like I am going nowhere on Google either. I would be grateful if someone could point me in the right direction. Thank you!

![image](https://user-images.githubusercontent.com/50542926/63754576-aef80080-c8e7-11e9-88b7-130262d75542.png)

**Comment by damithc** [comment]
![image](https://user-images.githubusercontent.com/1673303/63759937-f5059200-c8f0-11e9-96bd-b7bec651fcbf.png)

Why is the src folder shown in red? IIRC, those marked as _excluded_ are colored red. See if you can right-click, choose `Mark directory as` and `cancel exclusion`

**Comment by jeongyh99** [comment]
The issue has been resolved after the folders have been included. Thank you for the assistance 👍
