### ISSUE TITLE
Queries with regards to AY17/18 Sem 1 Paper from NUSLibraries

### ISSUE THREAD

**Issue by seanlowjk** [nus-cs2103-AY1920S1/forum#201]
Checking Answers for Questions 1 and 2 for CS2103T AY17/18 Paper!

![image](https://user-images.githubusercontent.com/42912708/69797754-39177400-120b-11ea-8196-54d6584fbbb6.png)

![Q1](https://user-images.githubusercontent.com/42912708/69797640-ffdf0400-120a-11ea-865a-6e6e3a7f5163.jpg)

**With Regards to Question 1, is this a correct way of representing a Facade Class?** 

![image](https://user-images.githubusercontent.com/42912708/69797772-40d71880-120b-11ea-9690-2a3cb63dc09b.png)

![Q2](https://user-images.githubusercontent.com/42912708/69797641-ffdf0400-120a-11ea-96fa-92f7bf9efb64.jpg)

**Comment by damithc** [comment]
Some comments:
Q1:
* `Data` need not be connected to every other class. It's enough if it is connected to the two `*Manager` classes.
* Don't overuse composition. e.g., It doesn't sound right to say a Person is part of a Project.
* Navigabilities are missing.
* `0..*` is same as `*`
* Allocation can be shown as an association class (see it's header comment)
* If you want, you  can use `<<Facade>>` to indicate a facade class.

Q2:
* No need to show a return value for constructors.
* The `Disk` object lifeline can terminate with an `X` as it goes out of scope when the `load()` method terminates.

**Comment by seanlowjk** [comment]
Ok Thanks Prof for the comments!

**Comment by lumos309** [comment]
Can I clarify, for the `Task` class in Q1, why isn't the arrow showing dependencies a one-way arrow? I.e., isn't it unambiguous from the code that the dependent knows about its dependencies, but not the other way around?

**Comment by damithc** [comment]
> Can I clarify, for the `Task` class in Q1, why isn't the arrow showing dependencies a one-way arrow? I.e., isn't it unambiguous from the code that the dependent knows about its dependencies, but not the other way around?

That's right. That's what I meant by `Navigabilities are missing`.

**Comment by lumos309** [comment]
> > Can I clarify, for the `Task` class in Q1, why isn't the arrow showing dependencies a one-way arrow? I.e., isn't it unambiguous from the code that the dependent knows about its dependencies, but not the other way around?
> 
> That's right. That's what I meant by `Navigabilities are missing`.

Oh, right! Thanks for the clarification.
