### ISSUE TITLE
could not import package in test folder

### ISSUE THREAD

**Issue by WilliamRyank** [nus-cs2103-AY1920S1/forum#23]
![1](https://user-images.githubusercontent.com/50859694/63828894-18cce480-c992-11e9-9be3-ffa17f4bdfa5.PNG)
![2](https://user-images.githubusercontent.com/50859694/63828895-18cce480-c992-11e9-8e24-486efdee0b16.PNG)
![3](https://user-images.githubusercontent.com/50859694/63828897-19657b00-c992-11e9-8ed4-46ba06be1244.PNG)
![4](https://user-images.githubusercontent.com/50859694/63828898-19657b00-c992-11e9-88aa-9f3f8b8981b7.PNG)

**Comment by damithc** [comment]
If the test code and the production code are in two different modules, you need to set the module containing the production code as a dependency of the test module. After that, you don't even need to import if the two classes are in matching packages.
![image](https://user-images.githubusercontent.com/1673303/63830550-01e0bf00-c99f-11e9-9996-69586d572d0e.png)

![image](https://user-images.githubusercontent.com/1673303/63830457-c219d780-c99e-11e9-8676-7cb7e1e762b0.png)

**Comment by WilliamRyank** [comment]
but my test module has no dependencies on top, im not sure why, but i followed the tutorial.

**Comment by WilliamRyank** [comment]
![5](https://user-images.githubusercontent.com/50859694/63839417-77518d00-c9a9-11e9-82d6-94cbe605f444.PNG)
![6](https://user-images.githubusercontent.com/50859694/63839419-77ea2380-c9a9-11e9-9afa-8c136022b956.PNG)

Still cant user the class prof

**Comment by damithc** [comment]
Looks like your `DukeTest` is not in any package? It should be in a package that matches `Deadline` class.

**Comment by damithc** [comment]
@WilliamRyank were you able to resolve?

**Comment by WilliamRyank** [comment]
Hi prof yes, thank you

**Comment by WilliamRyank** [comment]
J
