### ISSUE TITLE
Tag A-Jar or v0.1?

### ISSUE THREAD

**Issue by CarbonGrid** [nus-cs2103-AY1920S1/forum#24]
As per title. I noted this issue when feedback-bot was looking for A-Jar instead.
https://nus-cs2103-ay1920s1.github.io/website/schedule/week3/project.html#2-do-increments-a-moreoop-a-packages-a-junit-a-jar

Above section states to use v0.1

**Comment by damithc** [comment]
Good point. Apparently, GitHub automatically adds the version number as a tag. But that doesn't stop you from adding your own tag `A-Jar`.  The latter tag is purely for administrative purposes.

**Comment by CarbonGrid** [comment]
Noted.
