### ISSUE TITLE
Pushing branches to remote-repo

### ISSUE THREAD

**Issue by honhaochen** [nus-cs2103-AY1920S1/forum#25]
-----------------------------------------------------------------------
fatal: The current branch branch-level-7 has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin branch-level-7
-----------------------------------------------------------------------

Issue bot requested branches to be presented on the remote-repo
Thus, i checked out my branch-level-7 and try to push from there but i got this warning

Previously i just did branches, commited, then i checkout to my master and merge the branches without fast-forwarding

Any help on how to resolve this issue? Thanks!

**Comment by damithc** [comment]
Are you able to push the master branch?

**Comment by honhaochen** [comment]
Yeah, no problem doing that, and I have completed way beyond the other branches in the master branch then this problem pops out ._.

**Comment by damithc** [comment]
Did you try `git push -u origin branch-level-7` (that's how you push a new local branch to a remote repo)?

**Comment by honhaochen** [comment]
yeap, solved it. Thanks :D
