### ISSUE TITLE
run .bat in intellij

### ISSUE THREAD

**Issue by CoderStellaJ** [nus-cs2103-AY1920S1/forum#3]
Any detailed instructions on how to configure and run .bat/.sh in intellij for A-TextUiTesting ?

**Comment by damithc** [comment]
Have you followed [this tutorial](https://github.com/nus-cs2103-AY1920S1/duke/blob/master/tutorials/textUiTestingTutorial.md)?

**Comment by CoderStellaJ** [comment]
Yes, but in terms of the last step, do we need to set up the configuration again? I searched online and some people say need to add "External tools" for .bat

**Comment by j-lum** [comment]
What configuration are we looking at here? 

If you're using IntelliJ IDEA, you should be able to run the batch file from the terminal.

**Comment by j-lum** [comment]
I assume that you're on Windows since you're mention the `.bat` file:
![image](https://user-images.githubusercontent.com/22460123/63214824-edefbe80-c14f-11e9-9b66-1c94225720f1.png)

Then type in : 

![image](https://user-images.githubusercontent.com/22460123/63214840-1aa3d600-c150-11e9-94b9-bbf65c2b4405.png)

**Comment by CoderStellaJ** [comment]
Thanks a lot. I've found my problems.
**1. JNI error occurs during compilcation.**
My solution: This error may happen if you have changed your JDK version before. delete old JDK version and reopen duke project worked for me.
**2. If you have created multiple files for different classes.** Modified my .bat as follows
`javac  -cp ..\src -Xlint:none -d ..\bin ..\src\main\java\Task.java ..\src\main\java\Todo.java ..\src\main\java\Event.java ..\src\main\java\Deadline.java ..\src\main\java\DukeException.java ..\src\main\java\Duke.java`
