### ISSUE TITLE
javaFX: correct way to fix error for Launcher run? 

### ISSUE THREAD

**Issue by seanlowjk** [nus-cs2103-AY1920S1/forum#30]
![image](https://user-images.githubusercontent.com/42912708/64006282-96d0ed00-cb44-11e9-9827-6c980a93fa39.png)
In the event that you receive this error while trying to run the Launcher class
![image](https://user-images.githubusercontent.com/42912708/64006370-c4b63180-cb44-11e9-9b35-4b6ec969923b.png)
This is what I did to fix this error. To change the constructor to take in 0 parameters. 
![image](https://user-images.githubusercontent.com/42912708/64006675-5d4cb180-cb45-11e9-8ab0-0b68677f30b8.png)
Not sure if this is supposed to be intended to work as above, appreciate any advice to be given, thanks!

**Comment by j-lum** [comment]
From the official [JavaDoc](https://openjfx.io/javadoc/11/javafx.graphics/javafx/application/Application.html)  (emphasis mine). 

>Note that the start method is abstract and must be overridden. The init and stop methods have concrete implementations that do nothing.
>The Application subclass must be declared public and must have a **public no-argument constructor.**

Seems like you've arrived at the solution yourself. Great job!

**Comment by seanlowjk** [comment]
Ok thanks! :)
