### ISSUE TITLE
A-Gradle: Indentation for wrapped lines

### ISSUE THREAD

**Issue by C-likethis123** [nus-cs2103-AY1920S1/forum#31]
<img width="842" alt="Screenshot 2019-08-31 at 4 05 51 PM" src="https://user-images.githubusercontent.com/27060502/64061184-89316b00-cc09-11e9-91e1-bdc6e3591596.png">
Based on the style guide in the module website, indentation of wrapped lines should be 8 spaces more than the parent line. By this principle, it means that lines 18-20 should be indented with 16 lines. 

However, as seen in the picture below, when I run ./gradlew build, I get an error stating that the indentation of lines 18-20 should not be 16. I would like to get some advice on what is the correct indentation, do I follow the checkStyle warnings or the style guide? 
<img width="1438" alt="Screenshot 2019-08-31 at 4 06 14 PM" src="https://user-images.githubusercontent.com/27060502/64061183-83d42080-cc09-11e9-818a-2e56afd780a9.png">

**Comment by damithc** [comment]
Follow the coding standard. If required, reconfigure checkstyle to match the coding standard.

**Comment by C-likethis123** [comment]
Noted, thank you for your reply.

**Comment by shawnkoh** [comment]
Reopening this just to ask - is there a way to instruct IntelliJ to use 8 spaces for wrapped lines?
I can't find the setting anywhere; not even on stackoverflow / google.
