### ISSUE TITLE
Not Able To Run JUnit Tests

### ISSUE THREAD

**Issue by ManasVegi** [nus-cs2103-AY1920S1/forum#32]
![Screenshot (18)](https://user-images.githubusercontent.com/53593482/64061363-5046c580-cc0c-11e9-98f9-3d3cbe43f759.png)
I made a test folder in 'src', marked it as test source root, made the DukeTest.java with a dummyTest to try if it works.
No matter how many times I tried, I get an "Error: java: error: release version 13 not supported."

I tried running it using gradle.
I have tried keeping the test folder in different places, set up the project again and imported junit 5.4 from maven libraries since it was asking me to add android studio sdk to ass directly.

Couldn't really find a helpful solution on the internet. 
Any suggestions on how to go about with this? 

Addition1: Testing works just fine in a local repo of mine. The issue is in the dukerepo.

Addition2: I set up gradle. When I try running 'gradle test' it shows "Test events not received" everytime.

**Comment by j-lum** [comment]
Show me your `Project Structure` window. `Ctrl + Shift + Alt + S` on Windows.

**Comment by ManasVegi** [comment]
![Screenshot (19)](https://user-images.githubusercontent.com/53593482/64090042-ba31ad00-cd7b-11e9-963a-fb8f1870551e.png)

**Comment by damithc** [comment]
Looks like @j-lum missed this.
@ManasVegi were you able to resolve the issue?
