### ISSUE TITLE
JavaFX: unable to launch application 

### ISSUE THREAD

**Issue by C-likethis123** [nus-cs2103-AY1920S1/forum#33]
I have included these lines in my build.gradle file:
<img width="1438" alt="Screenshot 2019-08-31 at 6 38 31 PM" src="https://user-images.githubusercontent.com/27060502/64062838-9a38a700-cc1e-11e9-853d-458fac8ff119.png">
I have added the start method in the Duke.java file and a Launcher class according to JavaFX tutorial part 1. 
<img width="1013" alt="Screenshot 2019-08-31 at 6 40 45 PM" src="https://user-images.githubusercontent.com/27060502/64062860-de2bac00-cc1e-11e9-8130-c890591550ce.png">

However when I run ./gradlew build then ./gradlew run, I get directed to my Desktop and my command line interface looks like this:
<img width="1438" alt="Screenshot 2019-08-31 at 6 37 19 PM" src="https://user-images.githubusercontent.com/27060502/64062836-9442c600-cc1e-11e9-8d05-c4c520d9397f.png">

<img width="1438" alt="Screenshot 2019-08-31 at 6 37 11 PM" src="https://user-images.githubusercontent.com/27060502/64062841-9c9b0100-cc1e-11e9-8529-b4745badc2bf.png">

I am also unable to exit the program via the 'bye' command.

**Comment by j-lum** [comment]
Did you change your `mainClassName` in gradle to the `Launcher` class?

**Comment by minpyaemoe** [comment]
I also have the same issue, and i did not change the mainClassName to Launcher class in gradle.build file.

**Comment by ambervoong** [comment]
While I'm not sure if this will solve the specific problem, I did change mainClassName to Launcher and that made gradle run the application properly.

**Comment by C-likethis123** [comment]
I managed to solve the issue by changing mainClassName to Launcher, and commenting out my main method in the Duke class. 

Thank you for your inputs!
