### ISSUE TITLE
Level 10: cannot load fxml in Main

### ISSUE THREAD

**Issue by huiminlim** [nus-cs2103-AY1920S1/forum#35]
Hi I am receiving some issues when I try to run part 4 of Level-10. 
I have done as the tutorial has suggested, changed the main class in launcher to Main.class and I still receive the following error messages. 

![image](https://user-images.githubusercontent.com/43434313/64079360-2fb86180-cd19-11e9-84e2-69be70d1c2bc.png)
![image](https://user-images.githubusercontent.com/43434313/64079361-3cd55080-cd19-11e9-8cb0-8c54ab7c4114.png)

This is my project directory:
![image](https://user-images.githubusercontent.com/43434313/64079416-d7ce2a80-cd19-11e9-9ba7-ebf021f10f6f.png)

Is there any mistake I made and solution to this problem? Thanks!

**Comment by j-lum** [comment]
Hi, open the MainWindow.fxml file and verify that the controller specified is pointing to a class that actually exists. In your case, it would appear to be `duke.MainWindow` instead of just `MainWindow`.

**Comment by huiminlim** [comment]
Hi, thanks for help, works perfectly now!
