### ISSUE TITLE
Level 10: Null Pointer Exception for Tutorial Part 4

### ISSUE THREAD

**Issue by choongyx** [nus-cs2103-AY1920S1/forum#36]
Hi, I have followed the tutorial for the steps but is currently facing a Null Pointer Exception error when running Launcher.

![image](https://user-images.githubusercontent.com/39525563/64082352-4de58800-cd40-11e9-99d2-f8caede708b3.png)

which seems to be caused from Main.
![image](https://user-images.githubusercontent.com/39525563/64089179-6de46e00-cd77-11e9-81d4-7a4c5cd02b16.png)

This is my directory for the .fxml files.
![image](https://user-images.githubusercontent.com/39525563/64082374-8a18e880-cd40-11e9-8f67-d635a2894b0d.png)

Would appreciate if anyone knows how to solve this!

**Comment by damithc** [comment]
You can push the code to your fork (possibly in a branch) and share the link here. That will give the reader a more complete picture.

**Comment by choongyx** [comment]
This is the link to my code: https://github.com/choongyx/duke/tree/branch-Level-10

**Comment by j-lum** [comment]
![image](https://user-images.githubusercontent.com/22460123/64089803-6ecacf00-cd7a-11e9-9741-d7174790ffa6.png)

**Comment by choongyx** [comment]
It works now, thank you!
