### ISSUE TITLE
JavaFX scene throws cannot access evenTarget

### ISSUE THREAD

**Issue by lumwb** [nus-cs2103-AY1920S1/forum#37]
Under part 1 of the JavaFX tutorial, my stage.setScene(scene) and stage.show() methods within the overriden start(Stage stage) method throws cannot access javafx.event.eventTarget?

How should I resolve this?

**Comment by damithc** [comment]
Sharing the code of the said file and the exact exception might be helpful.

**Comment by lumwb** [comment]
![image](https://user-images.githubusercontent.com/25117015/64084764-ef7cd180-cd60-11e9-977d-3ca6309a2e26.png)

Apologies, please find attached the image of my Duke class.

**Comment by honhaochen** [comment]
Hi, I have the same issue. Did you resolved it?

**Comment by lumwb** [comment]
Yes. You could try following the steps for non-gradle, and adding the JavaFX references manually.

**Comment by honhaochen** [comment]
Alright, thank you!

**Comment by jxofficial** [comment]
It was working completely fine yesterday. But when I opened IntelliJ again today, I experienced the same error. Any ideas why?

> Yes. You could try following the steps for non-gradle, and adding the JavaFX references manually.

I tried to do this but I got "Two modules in a project cannot share the same content root" 
![image](https://user-images.githubusercontent.com/49927092/64138332-4224bf00-ce2f-11e9-8b7a-9ff2a3d4655c.png)

**Comment by ChrisKheng** [comment]
Maybe it would be good to remove the duplicated module by going to project structure >> module, and remove the 'main' module which is duplicated, cuz the issue of duplicated modules has just caused problems for my code when trying to use some javafx methods.

**Comment by jxofficial** [comment]
Ah yes, something useful to know. 

I have no idea what the duplicated modules are doing. Hopefully Prof can explain a little bit about classpath, duplicated modules, what gradle does behind the scenes etc.

Shall not mess with the structure for the time being, but its always good to know how to remove modules.

**Comment by j-lum** [comment]
Collaborative problem solving skills (demonstrated in this thread) are actually very valuable skills to have. 
Quite unfortunately: 

1. Classpaths in Java got even trickier after modules (Project Jigsaw) got introduced in Java 9.
1. Gradle is a complex tool meant to handle the rigours of equally complex code bases. A more nuanced discussion will likely fill up an entire textbook. 

If you want to know more about these topics (which are _very_ out of syllabus) I strongly encourage you to look it up yourself and teach your follow classmates about the things you've learnt; be the change you want to see! 

I'm available for consultation on Thursdays 1100 to 1330 at COM, just drop me a message on Slack/email with a list of things you want to discuss.
