### ISSUE TITLE
iP: Level 3: Java displays "?" instead of tick or cross

### ISSUE THREAD

**Issue by geshuming** [nus-cs2103-AY1920S1/forum#4]
**OS**: Microsoft Windows [Version 10.0.17134.950]
**Java**: 
```
java 11.0.2 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)
```
**Expected Result**:
```
list
1.[✓] add book
2.[✘] read book
```

**Actual Result**:
```
list
1.[?] add book
2.[?] read book
```

**Additional info**:
I tried echoing the unicode characters in `cmd.exe` and `bash.exe` and both worked fine. However, running jshell tells me that java is somehow not properly converting the unicode character into a string.

I used the partial solution given:
```java
    public String getStatusIcon() {
        return (isDone ? "\u2713" : "\u2718"); // return tick or X symbols
    }
```

Any help will be appreciated.

**Comment by damithc** [comment]
@geshuming don't worry about the code behavior on jshell (it is just a learning tool; not a production environment). It's fine as long as the code works on a regular console window. You are also free to change tick and x to something else. e.g., 
```
list
1.[+] add book
2.[ ] read book
```
