### ISSUE TITLE
Error in cs2113-feedback-bot for week 4

### ISSUE THREAD

**Issue by Inno97** [nus-cs2103-AY1920S1/forum#40]
" A version tagged A-MoorOOP is in the repo(❗️ try to do by next milestone)"
Bot checks for wrong tag
It's A-MoreOOP and not A-MoorOOP. 
( ͡° ͜ʖ ͡°)

**Comment by j-lum** [comment]
You might be in the wrong place.

**Comment by Inno97** [comment]
Oh whoops my bad.
