### ISSUE TITLE
javafx.controls not found

### ISSUE THREAD

**Issue by TSAI-HSIAO-HAN** [nus-cs2103-AY1920S1/forum#43]
When I tried to run Launcher, the FIndException always came out.
<img width="971" alt="Screenshot 2019-09-04 at 5 25 08 PM" src="https://user-images.githubusercontent.com/46244796/64243359-ce230d80-cf39-11e9-951a-1def9acc7978.png">

I follows the tutorial on Github, but still cannot figure out how to fix it.

This is the build.gradle file
<img width="493" alt="Screenshot 2019-09-04 at 5 25 30 PM" src="https://user-images.githubusercontent.com/46244796/64243402-de3aed00-cf39-11e9-924a-8e2ef309053a.png">

The configure and library
<img width="858" alt="Screenshot 2019-09-04 at 5 25 56 PM" src="https://user-images.githubusercontent.com/46244796/64243496-09254100-cf3a-11e9-8772-7c7f309fdb6d.png">
<img width="1056" alt="Screenshot 2019-09-04 at 5 26 22 PM" src="https://user-images.githubusercontent.com/46244796/64243507-0c203180-cf3a-11e9-9682-e96ef3b48278.png">
<img width="1078" alt="Screenshot 2019-09-04 at 5 26 36 PM" src="https://user-images.githubusercontent.com/46244796/64243530-18a48a00-cf3a-11e9-8453-6c33a2745740.png">

The javafx file path
<img width="605" alt="Screenshot 2019-09-04 at 5 24 51 PM" src="https://user-images.githubusercontent.com/46244796/64243599-307c0e00-cf3a-11e9-9fdd-359f5d2c8706.png">

**Comment by TSAI-HSIAO-HAN** [comment]
Error message
<img width="1225" alt="Screenshot 2019-09-04 at 6 46 22 PM" src="https://user-images.githubusercontent.com/46244796/64248703-7d64e200-cf44-11e9-9088-db19b7994a8d.png">

**Comment by damithc** [comment]
@j-lum any help?

**Comment by TSAI-HSIAO-HAN** [comment]
I solved this problem by right click the libs in Project Structure and add it in module manually.(Although I have other error after this, but that is related to jdk version)
