### ISSUE TITLE
Wrapped lines indentation auto-formatting

### ISSUE THREAD

**Issue by shawnkoh** [nus-cs2103-AY1920S1/forum#47]
Is there a way to instruct IntelliJ to use 8 spaces for wrapped lines?
I can't find the setting anywhere; not even on stackoverflow / google.
FWIW I'm using the Mac version 2019.2.1

**Comment by uggi121** [comment]
File -> Settings -> Editor -> Code Style -> Java -> Continuation Indent = 8

**Comment by damithc** [comment]
Thanks for the help @uggi121

**Comment by shawnkoh** [comment]
I can't find the same setting on my version (IntelliJ Ultimate Mac 2019.2.1)

**Comment by damithc** [comment]
Search in project settings?
![image](https://user-images.githubusercontent.com/1673303/64424280-3bba6f80-d0db-11e9-8f93-640f67cbb7c1.png)

**Comment by shawnkoh** [comment]
Got it! Thank you Prof!
