### ISSUE TITLE
Week 5 Duke Query

### ISSUE THREAD

**Issue by jeongyh99** [nus-cs2103-AY1920S1/forum#49]
The project for week 5 mentions "Add at least one extension of your choice, selected from category B, C, or D". Does this mean that we should implement one of the tasks from one of the category or implement of of the categories? e.g. would doing "B-TentativeScheduling" from category B suffice or do I need to complete B-*tasks? Thank you!

**Comment by uggi121** [comment]
Implementing all the tasks under that sub-section seems tedious and unnecessary. A pragmatic approach would be to discuss with your team and individually implement non-overlapping features relevant to the tP

**Comment by jeongyh99** [comment]
Thank you!

**Comment by damithc** [comment]
> The project for week 5 mentions "Add at least one extension of your choice, selected from category B, C, or D". Does this mean that we should implement one of the tasks from one of the category or implement of of the categories? e.g. would doing "B-TentativeScheduling" from category B suffice or do I need to complete B-*tasks? Thank you!

Just one item in one of the categories, not the whole category. :-)
