### ISSUE TITLE
IntelliJ created new package for me

### ISSUE THREAD

**Issue by jeongyh99** [nus-cs2103-AY1920S1/forum#5]
Suggestions and Auto Import somehow got disabled and it worked by setting src as my source directory. However, the IDE created a new directory for me and says I need to import java.main as it is now a package. Or something along those lines... is that going to be a problem for the bots to track my code?

**Comment by j-lum** [comment]
Hi, this problem can be solved by marking the `java` folder as your source root instead.

**Comment by jeongyh99** [comment]
Thank you!
