### ISSUE TITLE
Using javax.json library and its implementation

### ISSUE THREAD

**Issue by tanlk99** [nus-cs2103-AY1920S1/forum#50]
Oracle has a JSON processing library [javax.json](https://javaee.github.io/jsonp/) which is included in Java EE. Are we allowed to use this for the iP or tP? If we are, does this count as a third-party library for reuse purposes?

**Comment by j-lum** [comment]
Strongly suggest `jackson` instead since it's being used in AB-3.

**Comment by tanlk99** [comment]
Thanks for the suggestion! Do we have to credit it as stated in the [Policy on Reuse](https://nus-cs2103-ay1920s1.github.io/website/schedule/week4/project.html)?

**Comment by damithc** [comment]
> Thanks for the suggestion! Do we have to credit it as stated in the [Policy on Reuse](https://nus-cs2103-ay1920s1.github.io/website/schedule/week4/project.html)?

Not strictly necessary to explicitly acknowledge third party libraries in iP as iP doesn't have extensive documentation requirements. But you much acknowledge adapting code from others. In the tP, there is a place in the  documentation to list libraries used.

**Comment by damithc** [comment]
Also, the use of jackson is approved.
