### ISSUE TITLE
What is best practice for Serialization?

### ISSUE THREAD

**Issue by CarbonGrid** [nus-cs2103-AY1920S1/forum#52]
## Question

Since Java.io has a nifty way to serializing objects.
Is it recommended to always prefer using STL than writing base code from scratch?
Even if the object requires some obfuscation, the modification would be much easier while using STL.

## Intent

To reduce additional workload and size of code base than writing custom serialization to File for each required class. Implementing STL as CodeQuality improvement.

**Comment by j-lum** [comment]
You might want to rephrase your question a bit and use the appropriate terms to describe what you intend to do. 

More concretely, define the following terms in context:
- Obfuscation
- STL (are you a cpp guy?)
- Modification

You might also find that serialization in languages with reflection can be "automagically" derived.
If you're _really_ interested in digging very deep in that direction, you can read up on automatic codec derivation. I must warn you that it's a very steep and slippery slope of lens and zippers.

**Comment by CarbonGrid** [comment]
Sorry for some confusion.
What I meant:
Obfuscation - transient fields where we alternatively provide a hash in place.
STL - Wrong usage. I forgot STL doesn't mean Standard Libraries.
Modification - writing additional data alongside with serialized data.

**Comment by j-lum** [comment]
It would really help if you provided an example of what you intend to accomplish. Sounds like you're going to create a new data type that caches? 

The thing I always ask myself before starting on a task is "I could, but should I?"

If your aim is to make your code more maintainable, do you _really_ want to do it that way? 
Can you beat tested-and-proven libraries or at least provide some value which they _cannot_?
How much value can you provide with your code ("modification will be much easier")?

**Comment by CarbonGrid** [comment]
I think the only factors whether to use standard libraries or not are: 
-Ease of implementation and future extensions
-Visibility
-Size of Overheads

From this
`E0music festival2/12/2019T2000T1borrow bookE0movie4/12/2019T1355D0D1 Project Assignment5/12/2019T1357`

to this
`¬í sr 
duke.TaskListÑlM¬ã,Á L lst Ljava/util/ArrayList;xpsr java.util.ArrayListxÒ™Ça I sizexp   w   sr duke.task.Eventh¡NvDZ2Ì L att Ljava/time/LocalDateTime;xr duke.task.Taskk]ž9“ú Z isDoneL descriptiont Ljava/lang/String;xp t Music Festivalsr 
java.time.Ser•]„º"H²  xpw	  ãÄxsr duke.task.TodoÓ»æËgï—  xq ~ t borrow booksq ~  t Moviesq ~ w	  ã þxsr duke.task.DeadlineR66<˜I L byq ~ xq ~  t D1 Project Assignment | Team 1sq ~ w	  ã þxx`

**Comment by j-lum** [comment]
I strongly believe there's more that just those three points to consider when deciding on pulling in external dependencies. Look no more to the disaster that's the javascript (and also ruby) ecosystem.

In any case, you have yet made an argument on how changing 
>From this
E�0�music festival�2/12/2019T2000�T�1�borrow book�E�0�movie�4/12/2019T1355�D�0�D1 Project Assignment�5/12/2019T1357
>
>to this
¬í �sr duke.TaskListÑ�lM¬ã,Á� �L �lst �Ljava/util/ArrayList;xpsr �java.util.ArrayListx�Ò�™Ça�� �I �sizexp �w� �sr �duke.task.Eventh¡NvDZ2Ì� �L �att �Ljava/time/LocalDateTime;xr �duke.task.Taskk�]ž�9“ú� �Z �isDoneL �descriptiont �Ljava/lang/String;xp t �Music Festivalsr java.time.Ser•]„º�"H² xpw � �ã��Äxsr �duke.task.TodoÓ»æËgï—�� xq ~ ��t �borrow booksq ~ � t �Moviesq ~ �w � �ã þxsr �duke.task.DeadlineR66�<�˜I� �L �byq ~ �xq ~ � t �D1 Project Assignment | Team 1sq ~ �w � �ã� þxx

actually improves your code quality.

**Comment by CarbonGrid** [comment]
It's not explicitly shown but instead of avoidance of custom written parser and serialization should reduce the possibilities of bugs, I think? Since standard libraries are battle-tested.

IMO, I'm currently thinking that using standard libraries instead of custom written improves:
- Reliability
- Maintainability
- Testability
- Portability
- Reusability

Not too sure if that kind of concept is true.

**Comment by j-lum** [comment]
Well then you've answered your own question for your use case!
