### ISSUE TITLE
Error: Could not find or load main class Duke

### ISSUE THREAD

**Issue by nattanyz** [nus-cs2103-AY1920S1/forum#53]
## Environment
I am using IntelliJ 2019.2 on Windows 10, with JDK 12.0.2.

## Issue
Sometimes, I will be unable to run my code, as I will receive "Error: Could not find or load main class Duke", as shown in the following screenshot.
This error seems to appear intermittently. Occasionally, closing and reopening IntelliJ seems to fix it.
![image](https://user-images.githubusercontent.com/27663706/64501418-d5f50000-d2f3-11e9-82d4-bde9561f3086.png)
Please see my directory structure and part of my build.gradle file in the screenshot above.

I suspect this error has something to do with the Java Classpath, because the previous time it occurred, I was able to fix it by removing environment variables associated with older versions of Java.
However, I have not changed any environment variables in the past few days before this error occurred again this morning. Please see this screenshot of my environment variables:
![image](https://user-images.githubusercontent.com/27663706/64501525-4ac83a00-d2f4-11e9-8689-60c1657c2dfe.png)

`where java` seems to return the correct version of JDK:
![image](https://user-images.githubusercontent.com/27663706/64501901-0342ad80-d2f6-11e9-8960-b78f58e5a8f8.png)
The Project SDK in my project settings seems to be correct as well:
![image](https://user-images.githubusercontent.com/27663706/64501996-659bae00-d2f6-11e9-9e7b-96cbdb1b7e30.png)
Could I check if the content root is set correctly?
![image](https://user-images.githubusercontent.com/27663706/64502024-7a784180-d2f6-11e9-8645-d737ea374e4f.png)

Any help is greatly appreciated! :)

**Comment by nattanyz** [comment]
Hmm... seems like removing `package duke;` from Duke.java fixes this issue. Is this expected? Should Duke.java not be in the package? Furthermore, should the `mainClassName` in build.gradle be set to "Duke" or "duke.Duke"? Thanks!

**Comment by ChrisKheng** [comment]
I think the main course behind the issue "could not find or load main class Duke" is because java cannot find the `.class` file of Duke to load it. When Duke was in the `package duke`, was the `mainClassName` in your gradle is `duke.Duke`?

**Comment by Russell-Loh-NUS** [comment]
Hi @nattanyz , I faced a similar issue as yours when I packaged my app. 

Basically, there are two things you can do:
1. Under Edit Configurations...(option is beside the hammer on the top right) > Application > Duke, change the "Use classpath of module:" to duke.main instead of main
2. Under File > Project Structure... > Modules, remove the main and test modules (as this should already be under 'duke > main' & 'duke > test')

You shouldn't need to remove the `package duke;` from your Duke.java file and the mainClassName on Gradle should be left as `duke.Duke`. Hope this helps.

**Comment by damithc** [comment]
@nattanyz did you manage to resolve the problem? If you did, what was the solution?

**Comment by damithc** [comment]
presumed resolved. @nattanyz please reopen if needed.
Thanks @ChrisKheng and @Russell-Loh-NUS for your inputs.
