### ISSUE TITLE
Error: Could not open the jar produced by shadowJar

### ISSUE THREAD

**Issue by WilliamRyank** [nus-cs2103-AY1920S1/forum#54]
Hi, after generating the jar file using shadowJar i cant seem to open my jar file. Instead i got this error `Error: JavaFX runtime components are missing, and are required to run this application`. Any idea as why this happen? Thank you

**Comment by junnbang** [comment]
Hello, I also ran into the same problem. For me, it was due to the mainClassName in build.gradle. After i changed it to "Launcher", it will work.

> application {
    mainClassName = "Launcher"
}

**Comment by WilliamRyank** [comment]
Hi @junnbang, thank you for the help, managed to solve it.

**Comment by damithc** [comment]
@WilliamRyank did you use @junnbang's solution or was it something else?

**Comment by WilliamRyank** [comment]
Hi @damithc, yes i used his solution and it works now. Thanks.

**Comment by damithc** [comment]
Great. Thanks for the help @junnbang

**Comment by Al-Karid** [comment]
> Otherwise, check if you imported the javafx files into ur jar file before building it.

Hello, I have the same problem issued here. How's that import supposed to be done ?
