### ISSUE TITLE
Failed to enable assertions in IntelliJ despite adding "-ea"

### ISSUE THREAD

**Issue by shuiyao-sg** [nus-cs2103-AY1920S1/forum#55]
I followed the instruction given on [this site](https://stackoverflow.com/questions/18168257/where-to-add-compiler-options-like-ea-in-intellij-idea) to add "-ea" to my VM option (I also tried "-enableassertions") in Run Configuration. However, when I run the program there's no assertion error appearing (the program run as per normal). Can someone help me figure out how to solve this problem?

Here's the link for [my project](https://github.com/shuiyao-sg/duke.git). The relevant code can be found in the branch "branch-A-Assertions".

Below are the screenshots of my code snippet and IntelliJ setting.

![7ad2e1418b77d1ac59ccd3a8a19dd9f](https://user-images.githubusercontent.com/46176136/64613531-f367be00-d408-11e9-9494-b8f9830de307.png)
![ccb300f1a75a3c77c19623b2bb3893e](https://user-images.githubusercontent.com/46176136/64613540-f8c50880-d408-11e9-865f-3afc0debd9a5.png)

**Comment by CarbonGrid** [comment]
Is your build.gradle application targeting Launcher?

**Comment by shuiyao-sg** [comment]
> Is your build.gradle application targeting Launcher?

If you are referring to the application{ } block in build.gradle, I think yes.

![09f7b0e0e439380b300878761d13f01](https://user-images.githubusercontent.com/46176136/64618683-4cd4ea80-d413-11e9-9b03-2e9fb2a36031.png)

**Comment by CarbonGrid** [comment]
https://stackoverflow.com/questions/48396274/how-to-enable-assertions-in-the-gradle-run-task

**Comment by CarbonGrid** [comment]
Lol didn't test if -ea works configured in VM options. I assumed it did.

**Comment by shuiyao-sg** [comment]
> https://stackoverflow.com/questions/48396274/how-to-enable-assertions-in-the-gradle-run-task

It works! Thank you so much!

**Comment by damithc** [comment]
Thanks for the help @CarbonGrid
