### ISSUE TITLE
2 modules in a project cannot share same content root 

### ISSUE THREAD

**Issue by Kzrthikz** [nus-cs2103-AY1920S1/forum#56]
I am facing some issues with setting up the GUI. I tried to set up via gradle but am getting compilation errors like package javafx.Application does not exist. So I tried to manually download and import the lib into intellij but get the following error. 
<img width="1061" alt="Screenshot 2019-09-10 at 6 03 48 PM" src="https://user-images.githubusercontent.com/50614346/64613819-ac2dfd00-d409-11e9-83d1-6200cac84bdc.png">

**Comment by dawo5010** [comment]
Can you take a screenshot of the Modules tab?

**Comment by Kzrthikz** [comment]
<img width="1440" alt="Screenshot 2019-09-10 at 8 56 14 PM" src="https://user-images.githubusercontent.com/50614346/64615647-90c4f100-d40d-11e9-9b96-bf7f1aa51228.png">
<img width="1067" alt="Screenshot 2019-09-10 at 8 56 41 PM" src="https://user-images.githubusercontent.com/50614346/64615665-9b7f8600-d40d-11e9-9f08-ea9e8a504efc.png">

**Comment by dawo5010** [comment]
Delete 'main' under the Modules tab (don't touch the one under seedu.duke.duke) and that should fix it.

**Comment by Kzrthikz** [comment]
yes that fixed the problem! Thank you

**Comment by dawo5010** [comment]
Awesome, don't forget to close the issue :)

**Comment by damithc** [comment]
Thanks for the help @dawo5010
