### ISSUE TITLE
Error when executing jar file

### ISSUE THREAD

**Issue by ChangUo79** [nus-cs2103-AY1920S1/forum#58]
I have generated a new jar file using gradle. I am currently having issue executing the jar file as the same error keeps popping up:
![image](https://user-images.githubusercontent.com/54112270/64629717-4d2ab100-d426-11e9-81c3-b783e2a65bbd.png)

I have a launcher class which has the main method as well as a main class that extends javafx.application.Application but it seems that it is unable to detect either. Any solution on how to solve this problem?

Any help is appreciated.

**Comment by dawo5010** [comment]
See https://github.com/nus-cs2103-AY1920S1/forum/issues/54

Have you changed your shadowJar configuration to use Launcher as your main class instead?

**Comment by ChangUo79** [comment]
do you mean changing the mainClassName to Launcher?
![image](https://user-images.githubusercontent.com/54112270/64630371-8fa0bd80-d427-11e9-9426-ccf5eb5bfb8c.png)

**Comment by dawo5010** [comment]
Yep, then try `./gradlew shadowJar` again and see if it works :)

**Comment by ChangUo79** [comment]
Its working now. Thanks! Do I need to be concern with this even though the jar is working:
![image](https://user-images.githubusercontent.com/54112270/64630609-0f2e8c80-d428-11e9-8372-7b5f20a6a42f.png)

**Comment by dawo5010** [comment]
That looks like a print statement, so I dug through your code to find it. 

Your program uses the file /data/duke.txt relative to the directory that the jar file is launched. 
In your case, you likely launched the jar file from the `build` folder and that triggered the print statement in Line 46 of your Duke.java (according to [your latest commit here](https://github.com/ChangUo79/duke/blob/master/src/main/java/Duke.java)), hence printing 'File not found.'

**Comment by ChangUo79** [comment]
Ahh missed that out. Thanks for the help!

**Comment by damithc** [comment]
Thanks for the extensive help @dawo5010 👍
