### ISSUE TITLE
Changing Pushed Code

### ISSUE THREAD

**Issue by jeongyh99** [nus-cs2103-AY1920S1/forum#6]
If we already pushed our code to Github with the tag for a certain level, what are the steps we should take if we later realized it is wrong and want to change our code to rectify the problem, assuming we already have moved on to higher levels? Thank you!!

**Comment by j-lum** [comment]
This is more of a `git` problem than anything else. 
These would probably require a stronger understanding of git commits. 

1. Run `git rebase -i --root`. This will bring up a file in a text editor of your choice.
1. Find the commit that you want to rectify and change the word `pick` to `edit`.
1. Save and close the file. Now git will rewind your repo to the state at that commit. Don't worry, the rest of your commits are still there!
1. Make the changes that you want and commit those changes.
1. Now run `git rebase --continue`.

**Comment by damithc** [comment]
Adding to what @j-lum said, not to worry. We don't penalize for that kind of mistakes. Do note that Git allows you to change past commits. You  can always give that a try if you are interested in improving your Git skills beyond basics. If you want to go in that direction, here's a simple exercise to start with.
1. Push the latest version to your repo
1. Modify the most recent commit e.g., change the commit message
1. Force-push the modified commit to your fork to overwrite the 

(You'll have to Google a bit to find how to do the last two steps)

**Comment by jeongyh99** [comment]
Thank you Profs!
