### ISSUE TITLE
Process finished with exit code -1

### ISSUE THREAD

**Issue by jxofficial** [nus-cs2103-AY1920S1/forum#60]
## Environment
- IntelliJ version: IntelliJ IDEA Community Edition 2019.2
- Java version: jdk-12.0.2
- Operating system version: Windows 10 Home

## Issue
After squash and merge branch A-CodeQuality and pushing it to the remote, I pulled using source tree back to the local repo. I encountered merge conflicts, resolved them and committed. I then pushed my master branch.  After that, I am unable to run Launcher class. No stack trace. 

I have tried reverting back to my previous changes, but all my attempts showed the same error.

```
Process finished with exit code -1
```

My source tree looks like this.
![image](https://user-images.githubusercontent.com/49927092/64669221-5736c900-d493-11e9-97b0-86426dc662ee.png)

**Comment by dawo5010** [comment]
Thought I’d break the silence - cloned your code 2 days ago but no dice for me either. Mine returns an exit code of 255 instead, however.

Have you made any progress/found any new leads?

**Comment by jxofficial** [comment]
OOPS I JUST SOLVED IT. 

```
  public String hiMessage() {
        Logger logger = Logger.getLogger(MessageHandler.class.getName());
        logger.info("Ran after duke message");
        String message = "Hello! I'm Duke.\n";

        try {
            storage.readFromTasksFileToList(tasks);
            message += "This is where you left off previously:\n";
        } catch (FileNotFoundException e) {
            message += "Fetching failed. " + e.getMessage() + "\n";
            message += "Creating file now...\n";
            File dukeTxt = new File(Duke.filePath);
            try {
                dukeTxt.createNewFile();
                message += "File created! " + dukeTxt.getAbsolutePath() + "\n";
                message += "Reading file...\n";
            } catch (IOException ioe) {
                message += "\t File creation was not successful. \n";
                message += "\t Exiting system.";
                System.exit(-1);
            }

        }

        message += getAllTasksAsString();

        assert !message.isEmpty();

        return message;
    }
```

THIS BLOCK OF CODE ):

**Comment by damithc** [comment]
Thanks @wilfredbtan and @dawo5010
