### ISSUE TITLE
JNI exception

### ISSUE THREAD

**Issue by ROHITREDDYBALAM** [nus-cs2103-AY1920S1/forum#61]
- IntelliJ version: 2019.2
- Java version: jdk 11.0.4

## Issue
When I am trying to open the JAR file, it shows A JNI error has occurred, please check your installation and try again.
What could be the problem?

**Comment by damithc** [comment]
Solved? How?

**Comment by damithc** [comment]
It most likely to be the cause.  If you search for `A JNI error has occurred, please check your installation and try again`, some of the hits mention the cause as a mismatch of JDK's used to create and run the jar file.
Anyway, it's good that you fixed the problem yourself. 👍
