### ISSUE TITLE
error: package javafx.application does not exist

### ISSUE THREAD

**Issue by jolynnn8D** [nus-cs2103-AY1920S1/forum#62]
## Environment

- IntelliJ version: IntelliJ IDEA Ultimate 2019.2
<img width="815" alt="Screenshot 2019-09-11 at 3 40 15 PM" src="https://user-images.githubusercontent.com/41572120/64677611-7bea6b00-d4aa-11e9-8d76-283e2644588f.png">

## Issue

I am unable to implement JavaFX into my duke project - I've added the JavaFX library to the Project Structure as well as in the Edit Configurations window for both Duke and Launcher classes:
<img width="1022" alt="Screenshot 2019-09-11 at 3 41 39 PM" src="https://user-images.githubusercontent.com/41572120/64677741-c4a22400-d4aa-11e9-9d5d-ed0bdf124187.png">
<img width="1125" alt="Screenshot 2019-09-11 at 3 42 05 PM" src="https://user-images.githubusercontent.com/41572120/64677745-c66be780-d4aa-11e9-9eb7-f769dc9e0279.png">

However, when I run Launcher.main(), I get the following error even though the libraries seem to have been successfully imported within the code.
<img width="774" alt="Screenshot 2019-09-11 at 3 43 24 PM" src="https://user-images.githubusercontent.com/41572120/64677832-f1563b80-d4aa-11e9-83d3-7596a87c257c.png">

I have also attempted the Gradle method but it gives rise to another error which I suspect stems from the same issue:
<img width="774" alt="Screenshot 2019-09-11 at 3 44 38 PM" src="https://user-images.githubusercontent.com/41572120/64677922-1480eb00-d4ab-11e9-8f33-ff2408e4653f.png">

Any help would be greatly appreciated!! T__T

**Comment by Nanosync** [comment]
Have you tried re-importing the gradle project by hitting the refresh button in the Gradle tab of IntelliJ?

**Comment by jolynnn8D** [comment]
Yep :( I still get the same error.

**Comment by dawo5010** [comment]
Can you push your branch-Level-10 to your repo so that it can be cloned?

**Comment by damithc** [comment]
@jolynnn8D did @dawo5010's suggestion work?

**Comment by jolynnn8D** [comment]
Fixed by deleting the wrapper folder, running gradle wrapper, then gradlew run

**Comment by damithc** [comment]
> Fixed by deleting the wrapper folder, running gradle wrapper, then gradlew run

Got it. 

Thanks for the inputs @dawo5010
