### ISSUE TITLE
Issue when setting up Travis CI for group project and enabling auto-publishing of documentation

### ISSUE THREAD

**Issue by Sahilgat** [nus-cs2103-AY1920S1/forum#64]
Please read up on how to write a [good question](https://stackoverflow.com/help/how-to-ask)

## Environment

Describe your development environment

- IntelliJ version: IntelliJ IDEA 2019.2.2 (Community Edition)
- Java version: 11.0.4
- Operating system version: Windows 10 Home Version 1809

## Issue

![Error](https://user-images.githubusercontent.com/38809578/64851714-90fe0000-d64a-11e9-8b61-c48b9ffe23f8.PNG)
*Break*
![Error 2](https://user-images.githubusercontent.com/38809578/64852262-99a30600-d64b-11e9-8730-4296b1e8e18b.PNG)
*Break*
![Error 3](https://user-images.githubusercontent.com/38809578/64852266-9c056000-d64b-11e9-80a6-2b5cd0719f6d.PNG)
*Break*

Hi I've been having this issue when trying to set-up Travis CI for the group project and enable the auto-publishing of docs. The error seems to be the line in red, and I've tried running the gradle test and checkstyle tests individually with both pass so I'm not sure what's wrong. The only files changed were the readme.adoc and the .iml files that got added I believe from setting it up as an IntelliJ project. Does anyone have any idea what might be wrong?

**Comment by geshuming** [comment]
The problems is in the log :)

Lines 221 and 222

**Comment by Nanosync** [comment]
As @geshuming mentioned, those are the errors. To prevent such issues, you can try adding `*.iml` to `.gitignore` and remove the related files from the repository since they are generated by IntelliJ.

**Comment by Sahilgat** [comment]
Thanks for your help, silly of me to miss that!

**Comment by damithc** [comment]
Thanks for the help @Nanosync @geshuming 👍
