### ISSUE TITLE
cs2103-feedback-bot does not give feedback for students on Friday tutorial slots

### ISSUE THREAD

**Issue by seanlowjk** [nus-cs2103-AY1920S1/forum#65]
Hi! 

It appears for students who have Friday CS2103T tutorial slots, they do not have the relevant feedback given to them via the cs2103-feedback bot. 

![image](https://user-images.githubusercontent.com/42912708/64902651-e0414080-d6dd-11e9-8c3e-be85a758dec2.png)

May I know if this is intentional or there might be some bug? As me and my friends who take Friday Tutorial slots have yet to receive the Issue from the bot.

Thanks!

**Comment by damithc** [comment]
@cs2103-feedback-bot has run into a GitHub API quota restriction.  Will post feedback once it has been resolved.

**Comment by seanlowjk** [comment]
Ok thank you Prof! 😄
