### ISSUE TITLE
Clarification for week 5's increment as pull request

### ISSUE THREAD

**Issue by ChangUo79** [nus-cs2103-AY1920S1/forum#67]
Previously, I did my increments on a separate branch but did a pull instead of a pull request and had already merged. I wanted to do the pull request anyway, so I added a commit each to the CodeQuality branch and the Assertions branch and created the pull request this way:

![image](https://user-images.githubusercontent.com/54112270/64906425-01735280-d719-11e9-801a-18eceb60f760.png)

Afterwards, I did a pull on my master branch on sourcetree and it became like this:
![image](https://user-images.githubusercontent.com/54112270/64906459-a42bd100-d719-11e9-9f52-6746a3f68071.png)

Now I am slightly hesitant to pull for CodeQuality and Assertions as more problems might arise. I looked through and it seemed fine but felt that it would be better to have a second opinion before proceeding.

Any help is greatly appreciated!

**Comment by damithc** [comment]
Not entirely sure what the problem is. Pull the master (which might result in merging origin/master to your local master) and then push the updated master to your fork.

**Comment by ChangUo79** [comment]
My concern was whether the pull request was done correctly as the master was merged into A-Assertions and A-CodeQuality shown in the picture.

**Comment by damithc** [comment]
It's fine. it's a common practice to merge the master branch to a feature branch to make the feature branch up-to-date with the latest master.

**Comment by ChangUo79** [comment]
Understood! Thank you prof for the clarification 👍
