### ISSUE TITLE
Renaming the individual project after week 7

### ISSUE THREAD

**Issue by Parcly-Taxel** [nus-cs2103-AY1920S1/forum#68]
After week 7, our individual projects will have been graded. Can we rename our iP repositories to anything we like after that point?

(By tradition, all my repositories are named after real-world places: Selwyn [College, Cambridge], Kinross [Scotland], Dounreay [Scotland], Shinjuku [Tokyo] and here Bari [Italy]. In the first four repos listed here, the actual name of the repo &ndash; what goes into the URL &ndash; matches the assigned name as used in the readme. But we are under orders not to change the repo name for our Duke forks until an indeterminate time in the future, which is why this question was asked.)

**Comment by damithc** [comment]
We would like you to keep the repo name until all grading of the semester is over i.e., until end of this year. If you change the repo name, it could affect some parts of the module infrastructure such as [this page](https://nus-cs2103-ay1920s1.github.io/website/admin/ip-showcase.html).
