### ISSUE TITLE
Weird issue with importing project in IntelliJ

### ISSUE THREAD

**Issue by mannggoo** [nus-cs2103-AY1920S1/forum#7]
I tried to import the project in IntelliJ and faced the issue shown below where there is no 'next' button for me to proceed. I tried to resize it and it still looks like it got cut off. 

After some fiddling, it seems that pressing enter would work too. 

I would like to know if this issue is something related to my settings or due to my laptop model (dell xps13). I'm wondering if this might cause other problems down the line. 

![image](https://user-images.githubusercontent.com/43086377/63398191-60d29100-c3ff-11e9-8511-712fb36702b3.png)

**Comment by blimyj** [comment]
I had a similar problem. 
For me, disabling the Maven plugin seemed to make the "Next" button reappear.

Also curious if this will have any repercussions later on in the project.

**Comment by damithc** [comment]
@mannggoo resolved?

**Comment by damithc** [comment]
Presumed resolved. Closing. Reopen if needed.

**Comment by damithc** [comment]
Thanks @blimyj for offering your inputs.
