### ISSUE TITLE
Location is not set exception

### ISSUE THREAD

**Issue by irene-lly** [nus-cs2103-AY1920S1/forum#71]
## Environment

- IntelliJ version: 2019.2
- Java version: 11.0.4
- Operating system version: Windows 10

## Issue

I am having some problems opening the jar file, when I try running java -jar duke.jar this is what is shown:

![Screenshot (10)](https://user-images.githubusercontent.com/54141404/64935368-7793c880-d883-11e9-9515-585e9ec26ce6.png)

here is my project structure:

![Screenshot (12)](https://user-images.githubusercontent.com/54141404/64935380-867a7b00-d883-11e9-8ecf-78216a53c5d5.png)

and here is my Main.java:

![Screenshot (15)](https://user-images.githubusercontent.com/54141404/64935505-4798f500-d884-11e9-827a-d4fa26abee50.png)

does anyone know why this exception is shown?

**Comment by irene-lly** [comment]
Okay I have finally managed to solve it by marking the "resources" directory (../src/main/resources) as a "Resources Root" in intellij.

![Screenshot (16)](https://user-images.githubusercontent.com/54141404/64974670-d8e98500-d8df-11e9-80d9-977d94f8708e.png)

**Comment by damithc** [comment]
Thanks for sharing the solution @irene-lly 
It could be useful for others.
