### ISSUE TITLE
What if used JDK 12 instead of JDK 11 to compile?

### ISSUE THREAD

**Issue by seanlowjk** [nus-cs2103-AY1920S1/forum#74]
Hi important question! 

If we were to use JDK 12 to compile my program, will we be penalized if done so? 
Is it a must to use JDK 11 instead of JDK 12 to compile?

Thanks!

**Comment by damithc** [comment]
It's fine as long as your jar works in a computer that has Java 11 only. The safest way to ensure that is to actually use Java 11 to create the jar file.

**Comment by seanlowjk** [comment]
Ok thank you for the answer Prof! 😄
