### ISSUE TITLE
Doubt in sequence diagrams' loops

### ISSUE THREAD

**Issue by sandydays** [nus-cs2103-AY1920S1/forum#75]
This one of the sequence diagrams given in this week's material. 

![image](https://user-images.githubusercontent.com/50706672/65043865-608dcd00-d98e-11e9-8ca4-e8031e527f1d.png)

I have a doubt: Is it allowed to have the `while` loop outside an activation bar? I think I have seen both being drawn but I wasn't too sure. That is can a loop start before an activation bar is present i.e. considering the only three objects present are instances of `Foo`, `Bar`, and `Gee`? Would this answer change if there is are objects apart from these not shown in this diagram (from where the function calls like `do()` are coming, for example)?

**Comment by damithc** [comment]
Good question. In this case we can assume the while loop is in an activation bar that is not shown in the diagram.
![image](https://user-images.githubusercontent.com/1673303/65112914-bd7f9680-da13-11e9-85b8-a442218236c7.png)
When I wrote this question, 'missing activation bar' was not a _notation error_ that I had in mind. In UML diagrams it is usual to omit things that don't add value to the purpose of the diagram.

**Comment by sandydays** [comment]
I see Prof, thanks for clarifying!
