### ISSUE TITLE
Request to use Apache POI to write to excel files

### ISSUE THREAD

**Issue by EugeneTeu** [nus-cs2103-AY1920S1/forum#76]
## Library
Apache POI 
https://poi.apache.org/

## Purpose

We like to be able to read input from excel file and then write to excel file using the APACHE POI api 
(For TP)

**Comment by damithc** [comment]
Approved. Make sure it works on all platforms though, not just Windows.

**Comment by EugeneTeu** [comment]
Thanks prof!
