### ISSUE TITLE
Unable to find main class when running jar file

### ISSUE THREAD

**Issue by CoderStellaJ** [nus-cs2103-AY1920S1/forum#78]
When running jar file, it shows the following error:
`Error: Could not find or load main class duke.Launcher
Caused by: java.lang.ClassNotFoundException: duke.Launcher`

My guess is there is something wrong with class path setting, but haven't figured out how to solve it.

**Comment by ChrisKheng** [comment]
Uhm what did you put for the `mainClassName` in your `build.gradle` file though? Is it `duke.Launcher`? If yes, did you put your `Launcher` class inside a package called `duke`?

**Comment by CoderStellaJ** [comment]
> Uhm what did you put for the `mainClassName` in your `build.gradle` file though? Is it `duke.Launcher`? If yes, did you put your `Launcher` class inside a package called `duke`?

Yes. I put Launcher inside package duke and change mainclass in build.gradle. And gradle run command is successful without any problem. This error occurs only when I run my jar file.

**Comment by ChrisKheng** [comment]
Hmm did you push your latest change to github? Maybe I can help to inspect the jar error

**Comment by ChrisKheng** [comment]
By the way, did you use gradle to make the jar?

**Comment by CoderStellaJ** [comment]
> By the way, did you use gradle to make the jar?

Thanks a lot! I found the error. My fxml file path is wrong in the code and this causes the problem.

**Comment by damithc** [comment]
Thanks @ChrisKheng for the inputs. 👍
