### ISSUE TITLE
Bundling other dependencies into the shadowJar jar file

### ISSUE THREAD

**Issue by dragontho** [nus-cs2103-AY1920S1/forum#79]
Please read up on how to write a [good question](https://stackoverflow.com/help/how-to-ask)

## Environment

Describe your development environment

- IntelliJ version: 2019.2
- Java version: 11.0.3
- Operating system version: Windows 10
- _other packages' versions_ Gson 2.8.5

## Issue

I decided to use a third party library for my data storage called Gson instead of the normal .txt storage methods for extension D-Trivia. The application works fine when I was testing it in IntelliJ, however, when I exported it out to a jar file, there was a NullPointerException pointing to what should have been something that Gson took care of. My question now is is there a way to manually include the dependency inside shadowJar? And if such a solution is not possible, is there any other way to make it work through gradle configurations?

## Code/Log Trace

```
Caused by: java.lang.NullPointerException
        at seedu.duke.util.UI.viewAllTrivia(UI.java:147)
        at seedu.duke.commands.trivia.TriviaViewAllCommand.execute(TriviaViewAllCommand.java:12)
        at seedu.duke.Duke.getResponse(Duke.java:40)
        at seedu.duke.javafxui.MainWindow.handleUserInput(MainWindow.java:50)
```

```
dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.5.0'
    implementation 'com.google.code.gson:gson:2.8.5'
}
```

**Comment by dragontho** [comment]
Also, how does one change labels of issues?

**Comment by dragontho** [comment]
To add on, it is not only the trivia part that fails, anything regarding storage is not working, including the already implemented .txt storage for tasklist as well.

**Comment by joloong** [comment]
It might be due to your savedPath and triviaPath. The relative paths to the .txt and .json files from duke.jar and Duke.java are not the same.

**Comment by damithc** [comment]
> Also, how does one change labels of issues?

You can't. :-)

Regarding your problem, I recommend using gradle Shadow task to create the jar file. Most third party libraries has some documentation on how to add it to gradle.

You can also take reference from AB3 gradle file. I believe AB3 uses the jackson library for handling json files (similar to Gson).

**Comment by dragontho** [comment]
Oh sorry, I've found my own problem. It's because I did not implement my saving and loading properly from the beginning. Now I've fixed it. On another note, prof, would Gson be allowed for my iP?

**Comment by damithc** [comment]
Yes, it is possible to get approval for using GSon. Here's the procedure:
![image](https://user-images.githubusercontent.com/1673303/65156151-20e3e580-da61-11e9-805f-0aa98b7b03ae.png)

**Comment by damithc** [comment]
@joloong thanks for the inputs.
@dragontho close the issue if resolved.

**Comment by dragontho** [comment]
Alright thank you prof!
