### ISSUE TITLE
Housekeeping done after level-6?

### ISSUE THREAD

**Issue by ChangUo79** [nus-cs2103-AY1920S1/forum#8]
Are we penalized if we did the minimum requirement for a certain level and only do housekeeping/additional amendments after level 6? E.g. Minimum requirement for level-5 was to handle the 2 errors shown but I would like to make amendments after level-6.

Thanks for any help.

**Comment by damithc** [comment]
It's fine. Do as much as you can and learn as much as you can; that's the important thing. You should get full marks for iP as long as you put in a sincere effort.

**Comment by ChangUo79** [comment]
Understood and thank you prof for your reply.
