### ISSUE TITLE
Post Lecture Quiz

### ISSUE THREAD

**Issue by jeongyh99** [nus-cs2103-AY1920S1/forum#80]
Regarding the grading of the quiz, does the grader use the most recent completed quiz?
I have already completed my quiz and accidentally opened another quiz that I left unanswered. Will that affect how the grader? Thank you.

**Comment by damithc** [comment]
Such incomplete attempts will not be counted. We take the last _completed_ attempt.

**Comment by jeongyh99** [comment]
Thank you
