### ISSUE TITLE
Travis Tutorial/Requirements

### ISSUE THREAD

**Issue by jeongyh99** [nus-cs2103-AY1920S1/forum#82]
Regarding our pull requests, is it sufficient to follow the tutorial or do we have to ensure that Travis
"ticks" our pull requests? Thank you!!

**Comment by damithc** [comment]
CI pass is not a formal requirement from us. However, a CI failure indicates something is "broken" which might needs fixing, if only to prove to yourself that you know how to fix it.

**Comment by jeongyh99** [comment]
Thank you for the clarification!
