### ISSUE TITLE
Request to use Google Maps API and NUS Mods API

### ISSUE THREAD

**Issue by klementtan** [nus-cs2103-AY1920S1/forum#84]
## Library

Google Maps - https://cloud.google.com/maps-platform/?apis=maps
Nus Mods - https://api.nusmods.com/v2/

## Purpsoe

Google Maps to find the closest common meeting spaces for friends

NUS Mods API to find the common free time among friends

**Comment by damithc** [comment]
Approved. Do take note of `Recommendation-Minimal-Network` in our [project constraints](https://nus-cs2103-ay1920s1.github.io/website/admin/project-constraints.html#tp-constraints).

**Comment by klementtan** [comment]
Thank you prof!
