### ISSUE TITLE
Tangled Git logs

### ISSUE THREAD

**Issue by Parcly-Taxel** [nus-cs2103-AY1920S1/forum#87]
I have this strange Git log for [my personal repository](https://github.com/Parcly-Taxel/main) which is my fork of [my team's repository](https://github.com/AY1920S1-CS2103T-F11-4/main) (I am the team repo's owner):

![Strange Git log](https://user-images.githubusercontent.com/54175463/65345997-321e2500-dc0e-11e9-9be1-b939fc96cde6.png)

I've finished the two tutorials for week 6, and both requisite branches are present. I've also made a PR for my ``tutorial-adding-command`` branch, and the tangled lines in the log are a result of me pushing a few more commits to get used to the workflow and integrations for the team project, which caused my PR to have merge conflicts with the team repo's master branch (these conflicts, I fixed, naturally).

Do I need to do anything about the gnarly graphs? Or is it fine?

**Comment by damithc** [comment]
> Do I need to do anything about the gnarly graphs? Or is it fine?

From a module requirement perspective, it is fine. A neat version history is not a requirement.
