### ISSUE TITLE
Clarification on tP constraints

### ISSUE THREAD

**Issue by LeowWB** [nus-cs2103-AY1920S1/forum#92]
This is regarding `Constraints-Single-User` (shown [here](https://nus-cs2103-ay1920s1.github.io/website/admin/project-constraints.html)).

If I were to add a feature that allows sharing of data (via exporting and importing a file), would that count as a violation of the constraint? I figure it might not be because it should be quite easy for a single user to test this feature, but I just want to be sure.

**Comment by damithc** [comment]
Importing/exporting data is a good feature to have (in fact, can help the tester to load some data quickly). It does not violate the constraint as the feature can be used by a single user to transfer data from one computer to another.

**Comment by LeowWB** [comment]
I see. Thank you for the quick reply, Prof!
