### ISSUE TITLE
Bug: Post-Lecture LumiNUS Quiz 6 Sends to wrong URL

### ISSUE THREAD

**Issue by seanlowjk** [nus-cs2103-AY1920S1/forum#94]
![image](https://user-images.githubusercontent.com/42912708/65671649-2ef5bf80-e07a-11e9-875c-820ac6e56e9a.png)

![image](https://user-images.githubusercontent.com/42912708/65671634-29987500-e07a-11e9-86ea-d0aa3832d895.png)

There might be a bug here! 🐛

**Comment by damithc** [comment]
Thanks for the bug report @seanlowjk 
Fixed :shipit:
