### ISSUE TITLE
Request to use Jackson/standard JSON library 

### ISSUE THREAD

**Issue by lzw12345** [nus-cs2103-AY1920S1/forum#96]
## Library

{https://github.com/FasterXML/jackson}

## Purpsoe

{To aid in storing and reading data in JSON format}

**Comment by damithc** [comment]
Approved.
Actually, Jackson is being used in AB3 already.

**Comment by lzw12345** [comment]
Actually this is for my IP, is it still ok?

**Comment by damithc** [comment]
Yes, OK. Remember to configure gradle so that the library is packaged into the jar file.
