### ISSUE TITLE
Duke last line truncated when wrapText="true"

### ISSUE THREAD

**Issue by shuiyao-sg** [nus-cs2103-AY1920S1/forum#98]
## Issue:
When I set wrapText="true" in the Label "dialog" in DialogBox.fxml, the last line of my list will always be truncated and replaced with ellipses. May I know how should I fix it?

Here's my repo if you want to replicate it https://github.com/shuiyao-sg/duke.git
The code can be found in `branch-GUI`

Here's how the bug looks like:
![b7136fbf95d89c5e10a725b6e9a6139](https://user-images.githubusercontent.com/46176136/65759953-a72db500-e14e-11e9-9d43-07c202329b1d.png)

Here's the screenshot of DialogBox.fxml:
![image](https://user-images.githubusercontent.com/46176136/65760020-ce848200-e14e-11e9-8478-10e7deabd588.png)

Here's the screenshot of MainWindow.fxml:
![image](https://user-images.githubusercontent.com/46176136/65760087-e52ad900-e14e-11e9-92d7-8c770cef80b4.png)

What's strange is that when I ask my friend to replicate this problem, it seems that he doesn't have such kind of issue with the same code (he's using Linux system):
![image](https://user-images.githubusercontent.com/46176136/65760335-684c2f00-e14f-11e9-9c85-55f58004e459.png)

## Something not sure whether it is related to this problem:
When I run Duke, I always get this warning of wrong JavaFx runtime version:
![image](https://user-images.githubusercontent.com/46176136/65760517-c11bc780-e14f-11e9-917e-74f17d911c1a.png)

## Environment:
OS: Windows 10
IntelliJ version: 2019.2
Java version:
java 11.0.1 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)

**Comment by Cronyxx** [comment]
Did you try removing the max height field from your DialogBox.fxml?

**Comment by shuiyao-sg** [comment]
> Did you try removing the max height field from your DialogBox.fxml?

I tried but it doesn't work.

**Comment by junnbang** [comment]
Maybe you can try setting your VBox / Hbox (which ever u use to wrap your content) Min height/width to USE_PREF_SIZE via the SceneBuilder.

**Comment by j-lum** [comment]
For the warning, refer to this issue: https://github.com/nus-cs2103-AY1819S2/forum/issues/30

As for JavaFX styling issues, in theory there should be no differences across platforms. However, weird quirks like this are not unheard of.  If @junnbang's suggestion does not work, you can investigate using a listener to dynamically resize the dialog box to fit as a workaround.

**Comment by shuiyao-sg** [comment]
> Maybe you can try setting your VBox / Hbox (which ever u use to wrap your content) Min height/width to USE_PREF_SIZE via the SceneBuilder.

It does not work as well...Thanks anyways!

**Comment by shuiyao-sg** [comment]
> For the warning, refer to this issue: [nus-cs2103-AY1819S2/forum#30](https://github.com/nus-cs2103-AY1819S2/forum/issues/30)
> 
> As for JavaFX styling issues, in theory there should be no differences across platforms. However, weird quirks like this are not unheard of. If @junnbang's suggestion does not work, you can investigate using a listener to dynamically resize the dialog box to fit as a workaround.

I think my friend mistakenly ran the code from my master branch (with wrapText=false), where it should have been from branch-GUI. So it should not be a platform-related problem. So I guess there are some problem with my code...

**Comment by sandydays** [comment]
What I did was that I changed from `Label` to the shape `Text` in both my `MainWindow.java` and `DialogBox.fxml` (changed in `DialogBox.fxml` using Scene Builder). I had read up a bit on online forums and it seems that `Label` does not adjust based on the size of your text (in this case, the tasks that Duke prints), so there was a recommendation to use `Text` shape instead. Let me know if this works!

**Comment by shuiyao-sg** [comment]
> What I did was that I changed from `Label` to the shape `Text` in both my `MainWindow.java` and `DialogBox.fxml` (changed in `DialogBox.fxml` using Scene Builder). I had read up a bit on online forums and it seems that `Label` does not adjust based on the size of your text (in this case, the tasks that Duke prints), so there was a recommendation to use `Text` shape instead. Let me know if this works!

It works! Thanks!

**Comment by damithc** [comment]
Thanks everyone for the inputs
@shuiyao-sg go ahead and close if the issue is resolved.

**Comment by shuiyao-sg** [comment]
> Thanks everyone for the inputs
> @shuiyao-sg go ahead and close if the issue is resolved.

Thanks Prof!
